apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: yetbota-infra
    labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: yetbota
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:tYqe2biiEw==,iv:s80mMh511Y37xytHxB4Tz1rKsX9uyccwmzFtLP7U+kw=,tag:CziVjsvO0iEs626ne9iqsw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1rMREvWDDaRsgjop1lA8FbMTBtxhtMdKizEGt4GSkCL9kN71RIGmyVt+Xg==,iv:V247iC4EJLGwzKBJR8n3clLLZUZAWIgIsrYPmM5rO+4=,tag:EeUmzs+v4subPt6JdAfC9A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:WpL21Ca/rPE0LA==,iv:asdSj/j36fyo4RnDA0XQ0aExnBksGRiYVIHUi4+N3HQ=,tag:j9xU7zOzc1lJQ4kdVCHUlQ==,type:str]
sops:
    age:
        - recipient: age1aaplqegrnem7x5k89rtn2mfrajkjkapf0lamfw6fdjk9ru4e65cs7qnq7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK2hlRTNVYWtNZ2RaN21t
            akVrbnBzbEdUSks3bUNsUVhRMElUTndYTTBFCmI3bnB5R3JSRm5PTm9VS3NlSGFx
            NytDaUgzMWc2K3gvbmMvdUZuZU1EQ0EKLS0tIDFYbm9xdDV1cXhhaUV6WENuSVBy
            SzFTaTVqWmFwY0YzZVF4cTQ4aEVYME0Kul72fp8ct6rjv+M2WaBTNbkvT/HtHZVE
            ZhrFfEq3RPXWb43nVC1LR2nAfIdD7ACjZLmyq5KQTSyURQXcWQe0Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T11:30:32Z"
    mac: ENC[AES256_GCM,data:b0jz5ELaDr993C3M3gXfKXVMQaE+dsVjhaXLCPGw6vt/wHJc3WG7BGV6ljyIj6JbVBimNoBRmatMuznqcXcfPNk1E4ejmRXRfU0Qlh2gv/SoJQidyO1aZfXDxzYPwqynQmXgS7dNx3b8Lcz3TBUTk7fYgHfIfL38EC+FiQysjfs=,iv:NWelDwLw3FiqAQFHcVBwDT9LVv7xrJ744qKZi7mweyM=,tag:bPzUrCGX0+NRLrryHtmcuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
