// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Photo is an object representing the database table.
type Photo struct {
	ID             string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	BucketProvider string    `boil:"bucket_provider" json:"bucket_provider" toml:"bucket_provider" yaml:"bucket_provider"`
	MimeType       string    `boil:"mime_type" json:"mime_type" toml:"mime_type" yaml:"mime_type"`
	URL            string    `boil:"url" json:"url" toml:"url" yaml:"url"`
	CreatedAt      time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *photoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L photoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PhotoColumns = struct {
	ID             string
	BucketProvider string
	MimeType       string
	URL            string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	BucketProvider: "bucket_provider",
	MimeType:       "mime_type",
	URL:            "url",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var PhotoTableColumns = struct {
	ID             string
	BucketProvider string
	MimeType       string
	URL            string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "photos.id",
	BucketProvider: "photos.bucket_provider",
	MimeType:       "photos.mime_type",
	URL:            "photos.url",
	CreatedAt:      "photos.created_at",
	UpdatedAt:      "photos.updated_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var PhotoWhere = struct {
	ID             whereHelperstring
	BucketProvider whereHelperstring
	MimeType       whereHelperstring
	URL            whereHelperstring
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	ID:             whereHelperstring{field: "\"photos\".\"id\""},
	BucketProvider: whereHelperstring{field: "\"photos\".\"bucket_provider\""},
	MimeType:       whereHelperstring{field: "\"photos\".\"mime_type\""},
	URL:            whereHelperstring{field: "\"photos\".\"url\""},
	CreatedAt:      whereHelpertime_Time{field: "\"photos\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"photos\".\"updated_at\""},
}

// PhotoRels is where relationship names are stored.
var PhotoRels = struct {
	ProfilePhotoUsers string
}{
	ProfilePhotoUsers: "ProfilePhotoUsers",
}

// photoR is where relationships are stored.
type photoR struct {
	ProfilePhotoUsers UserSlice `boil:"ProfilePhotoUsers" json:"ProfilePhotoUsers" toml:"ProfilePhotoUsers" yaml:"ProfilePhotoUsers"`
}

// NewStruct creates a new relationship struct
func (*photoR) NewStruct() *photoR {
	return &photoR{}
}

func (o *Photo) GetProfilePhotoUsers() UserSlice {
	if o == nil {
		return nil
	}

	return o.R.GetProfilePhotoUsers()
}

func (r *photoR) GetProfilePhotoUsers() UserSlice {
	if r == nil {
		return nil
	}

	return r.ProfilePhotoUsers
}

// photoL is where Load methods for each relationship are stored.
type photoL struct{}

var (
	photoAllColumns            = []string{"id", "bucket_provider", "mime_type", "url", "created_at", "updated_at"}
	photoColumnsWithoutDefault = []string{"bucket_provider", "mime_type", "url"}
	photoColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	photoPrimaryKeyColumns     = []string{"id"}
	photoGeneratedColumns      = []string{}
)

type (
	// PhotoSlice is an alias for a slice of pointers to Photo.
	// This should almost always be used instead of []Photo.
	PhotoSlice []*Photo
	// PhotoHook is the signature for custom Photo hook methods
	PhotoHook func(context.Context, boil.ContextExecutor, *Photo) error

	photoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	photoType                 = reflect.TypeOf(&Photo{})
	photoMapping              = queries.MakeStructMapping(photoType)
	photoPrimaryKeyMapping, _ = queries.BindMapping(photoType, photoMapping, photoPrimaryKeyColumns)
	photoInsertCacheMut       sync.RWMutex
	photoInsertCache          = make(map[string]insertCache)
	photoUpdateCacheMut       sync.RWMutex
	photoUpdateCache          = make(map[string]updateCache)
	photoUpsertCacheMut       sync.RWMutex
	photoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var photoAfterSelectMu sync.Mutex
var photoAfterSelectHooks []PhotoHook

var photoBeforeInsertMu sync.Mutex
var photoBeforeInsertHooks []PhotoHook
var photoAfterInsertMu sync.Mutex
var photoAfterInsertHooks []PhotoHook

var photoBeforeUpdateMu sync.Mutex
var photoBeforeUpdateHooks []PhotoHook
var photoAfterUpdateMu sync.Mutex
var photoAfterUpdateHooks []PhotoHook

var photoBeforeDeleteMu sync.Mutex
var photoBeforeDeleteHooks []PhotoHook
var photoAfterDeleteMu sync.Mutex
var photoAfterDeleteHooks []PhotoHook

var photoBeforeUpsertMu sync.Mutex
var photoBeforeUpsertHooks []PhotoHook
var photoAfterUpsertMu sync.Mutex
var photoAfterUpsertHooks []PhotoHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Photo) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Photo) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Photo) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Photo) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Photo) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Photo) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Photo) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Photo) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Photo) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range photoAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPhotoHook registers your hook function for all future operations.
func AddPhotoHook(hookPoint boil.HookPoint, photoHook PhotoHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		photoAfterSelectMu.Lock()
		photoAfterSelectHooks = append(photoAfterSelectHooks, photoHook)
		photoAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		photoBeforeInsertMu.Lock()
		photoBeforeInsertHooks = append(photoBeforeInsertHooks, photoHook)
		photoBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		photoAfterInsertMu.Lock()
		photoAfterInsertHooks = append(photoAfterInsertHooks, photoHook)
		photoAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		photoBeforeUpdateMu.Lock()
		photoBeforeUpdateHooks = append(photoBeforeUpdateHooks, photoHook)
		photoBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		photoAfterUpdateMu.Lock()
		photoAfterUpdateHooks = append(photoAfterUpdateHooks, photoHook)
		photoAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		photoBeforeDeleteMu.Lock()
		photoBeforeDeleteHooks = append(photoBeforeDeleteHooks, photoHook)
		photoBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		photoAfterDeleteMu.Lock()
		photoAfterDeleteHooks = append(photoAfterDeleteHooks, photoHook)
		photoAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		photoBeforeUpsertMu.Lock()
		photoBeforeUpsertHooks = append(photoBeforeUpsertHooks, photoHook)
		photoBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		photoAfterUpsertMu.Lock()
		photoAfterUpsertHooks = append(photoAfterUpsertHooks, photoHook)
		photoAfterUpsertMu.Unlock()
	}
}

// One returns a single photo record from the query.
func (q photoQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Photo, error) {
	o := &Photo{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for photos")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Photo records from the query.
func (q photoQuery) All(ctx context.Context, exec boil.ContextExecutor) (PhotoSlice, error) {
	var o []*Photo

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to Photo slice")
	}

	if len(photoAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Photo records in the query.
func (q photoQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count photos rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q photoQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if photos exists")
	}

	return count > 0, nil
}

// ProfilePhotoUsers retrieves all the user's Users with an executor via profile_photo_id column.
func (o *Photo) ProfilePhotoUsers(mods ...qm.QueryMod) userQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"users\".\"profile_photo_id\"=?", o.ID),
	)

	return Users(queryMods...)
}

// LoadProfilePhotoUsers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (photoL) LoadProfilePhotoUsers(ctx context.Context, e boil.ContextExecutor, singular bool, maybePhoto any, mods queries.Applicator) error {
	var slice []*Photo
	var object *Photo

	if singular {
		var ok bool
		object, ok = maybePhoto.(*Photo)
		if !ok {
			object = new(Photo)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePhoto)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePhoto))
			}
		}
	} else {
		s, ok := maybePhoto.(*[]*Photo)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePhoto)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePhoto))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &photoR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &photoR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.profile_photo_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load users")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice users")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ProfilePhotoUsers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &userR{}
			}
			foreign.R.ProfilePhoto = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ProfilePhotoID) {
				local.R.ProfilePhotoUsers = append(local.R.ProfilePhotoUsers, foreign)
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.ProfilePhoto = local
				break
			}
		}
	}

	return nil
}

// AddProfilePhotoUsers adds the given related objects to the existing relationships
// of the photo, optionally inserting them as new records.
// Appends related to o.R.ProfilePhotoUsers.
// Sets related.R.ProfilePhoto appropriately.
func (o *Photo) AddProfilePhotoUsers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*User) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ProfilePhotoID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"users\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"profile_photo_id"}),
				strmangle.WhereClause("\"", "\"", 2, userPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ProfilePhotoID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &photoR{
			ProfilePhotoUsers: related,
		}
	} else {
		o.R.ProfilePhotoUsers = append(o.R.ProfilePhotoUsers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &userR{
				ProfilePhoto: o,
			}
		} else {
			rel.R.ProfilePhoto = o
		}
	}
	return nil
}

// SetProfilePhotoUsers removes all previously related items of the
// photo replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.ProfilePhoto's ProfilePhotoUsers accordingly.
// Replaces o.R.ProfilePhotoUsers with related.
// Sets related.R.ProfilePhoto's ProfilePhotoUsers accordingly.
func (o *Photo) SetProfilePhotoUsers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*User) error {
	query := "update \"users\" set \"profile_photo_id\" = null where \"profile_photo_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ProfilePhotoUsers {
			queries.SetScanner(&rel.ProfilePhotoID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.ProfilePhoto = nil
		}
		o.R.ProfilePhotoUsers = nil
	}

	return o.AddProfilePhotoUsers(ctx, exec, insert, related...)
}

// RemoveProfilePhotoUsers relationships from objects passed in.
// Removes related items from R.ProfilePhotoUsers (uses pointer comparison, removal does not keep order)
// Sets related.R.ProfilePhoto.
func (o *Photo) RemoveProfilePhotoUsers(ctx context.Context, exec boil.ContextExecutor, related ...*User) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ProfilePhotoID, nil)
		if rel.R != nil {
			rel.R.ProfilePhoto = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("profile_photo_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ProfilePhotoUsers {
			if rel != ri {
				continue
			}

			ln := len(o.R.ProfilePhotoUsers)
			if ln > 1 && i < ln-1 {
				o.R.ProfilePhotoUsers[i] = o.R.ProfilePhotoUsers[ln-1]
			}
			o.R.ProfilePhotoUsers = o.R.ProfilePhotoUsers[:ln-1]
			break
		}
	}

	return nil
}

// Photos retrieves all the records using an executor.
func Photos(mods ...qm.QueryMod) photoQuery {
	mods = append(mods, qm.From("\"photos\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"photos\".*"})
	}

	return photoQuery{q}
}

// FindPhoto retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPhoto(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Photo, error) {
	photoObj := &Photo{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"photos\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, photoObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from photos")
	}

	if err = photoObj.doAfterSelectHooks(ctx, exec); err != nil {
		return photoObj, err
	}

	return photoObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Photo) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no photos provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(photoColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	photoInsertCacheMut.RLock()
	cache, cached := photoInsertCache[key]
	photoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			photoAllColumns,
			photoColumnsWithDefault,
			photoColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(photoType, photoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(photoType, photoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"photos\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"photos\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into photos")
	}

	if !cached {
		photoInsertCacheMut.Lock()
		photoInsertCache[key] = cache
		photoInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Photo.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Photo) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	photoUpdateCacheMut.RLock()
	cache, cached := photoUpdateCache[key]
	photoUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			photoAllColumns,
			photoPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update photos, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"photos\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, photoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(photoType, photoMapping, append(wl, photoPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update photos row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for photos")
	}

	if !cached {
		photoUpdateCacheMut.Lock()
		photoUpdateCache[key] = cache
		photoUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q photoQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for photos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for photos")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PhotoSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), photoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"photos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, photoPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in photo slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all photo")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Photo) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no photos provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(photoColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	photoUpsertCacheMut.RLock()
	cache, cached := photoUpsertCache[key]
	photoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			photoAllColumns,
			photoColumnsWithDefault,
			photoColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			photoAllColumns,
			photoPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert photos, could not build update column list")
		}

		ret := strmangle.SetComplement(photoAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(photoPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert photos, could not build conflict column list")
			}

			conflict = make([]string, len(photoPrimaryKeyColumns))
			copy(conflict, photoPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"photos\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(photoType, photoMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(photoType, photoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert photos")
	}

	if !cached {
		photoUpsertCacheMut.Lock()
		photoUpsertCache[key] = cache
		photoUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Photo record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Photo) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no Photo provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), photoPrimaryKeyMapping)
	sql := "DELETE FROM \"photos\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from photos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for photos")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q photoQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no photoQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from photos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for photos")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PhotoSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(photoBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), photoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"photos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, photoPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from photo slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for photos")
	}

	if len(photoAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Photo) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPhoto(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PhotoSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PhotoSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), photoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"photos\".* FROM \"photos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, photoPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in PhotoSlice")
	}

	*o = slice

	return nil
}

// PhotoExists checks if the Photo row exists.
func PhotoExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"photos\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if photos exists")
	}

	return exists, nil
}

// Exists checks if the Photo row exists.
func (o *Photo) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PhotoExists(ctx, exec, o.ID)
}
