app:
  name: Yet Bota - AI Service
  version: 0.0.1
cors:
  hosts:
    - localhost:3000
    - localhost:3001
debug: ${debug}
grpc:
  port: ${grpcPort}
  keepalive:
    time: ${grpcKeepaliveTime}
    timeout: ${grpcKeepaliveTimeout}
    min_time: ${grpcKeepaliveMinTime}
    permit_without_stream: ${grpcKeepalivePermitWithoutStream}
rest:
  idle_timeout: ${restIdleTimeout}
  port: ${restPort}
  read_timeout: ${restReadTimeout}
  write_timeout: ${restWriteTimeout}
embedding:
  model: ${embeddingModel}
  dimensions: ${embeddingDimensions}
  base_url: ${embeddingBaseURL}
  api_key: ${embeddingAPIKey}
  timeout_seconds: ${embeddingTimeoutSeconds}
vectordb:
  url: ${vectordbURL}
  api_key: ${vectordbAPIKey}
  collection: ${vectordbCollection}
llm:
  model: ${llmModel}
  api_key: ${llmAPIKey}
  max_tokens: ${llmMaxTokens}
  temperature: ${llmTemperature}
  timeout_seconds: ${llmTimeoutSeconds}