apiVersion: v1
kind: Secret
metadata:
    name: ai-service-secret
    namespace: yetbota
    labels:
        app.kubernetes.io/name: ai-service
        app.kubernetes.io/part-of: yetbota
type: Opaque
stringData:
    GEMINI__API_KEY: ENC[AES256_GCM,data:UDIECBeLoKAKL9NQZ2ZCPsr3RIvUKbEo4VZQcTqb9pbCL4jt8Bg8,iv:y51j/nzrv50T1qA+sFxnZb3X8ZCkndQr1tMc8kxhhQo=,tag:2uDaDXKFuYG1uzAdZo5xgQ==,type:str]
    WEAVIATE__API_KEY: ENC[AES256_GCM,data:LwiB6KudKUn/22kesVi6PXVny0/dm7htMa+hwShPeZ438SLd7Gbg+Z5PXu1NEaaDG95PIbU8xXgWNLJeP4E8EHy9BFK4oBRudH7Aw6FYh8XNarGveFlQbQ==,iv:Y8+oukxG46qySeec/0de6XMcNcY2CXtrzTjTKqM30rQ=,tag:9VOFLyM/Kn2r5cURbvqOjw==,type:str]
    NEO4J__PASSWORD: ENC[AES256_GCM,data:tleH1p4jtgDg,iv:O+5fWy0zcIIpbl1NlJi+5l6oTdFqnchbjnSMH6lT8Uk=,tag:H9bzqh2nzlARTwk62QpOCg==,type:str]
    RABBITMQ__URI: ENC[AES256_GCM,data:z1ZppcrUPvobqa/zS/Pqt9fYEA8JdQGxhAO/xBLFL6THDe3OSIDs1BpMBZagzI002VQAErmgCzuziWaVOw==,iv:NKw5fhFxZMdAK0ritoUiX7sCS9XLKvmRc9QhAMV7imE=,tag:H2dpzN7MuOZehudhgAUkBw==,type:str]
sops:
    age:
        - recipient: age1aaplqegrnem7x5k89rtn2mfrajkjkapf0lamfw6fdjk9ru4e65cs7qnq7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S0w3NDNWNzh1THRjcXJj
            RDRIQXdEbGNlRjNuMkpSTGE3ZU1abDNsUkFBCmVYUWUvbndoSzR0eVluTkN3Y0p5
            Wkg4VDlvNjlxcEF6eDliRXVVMlZHc28KLS0tIEk5c3NCOU5RUWpVZTJMNEYxTERr
            WHdJdXFyN2hDaE1EWjRxU2JENHdxMVUKLWJ0ApvoOjD32SlCfGy7o94J5FU+xMls
            ly1A5wXRZgaVZr+io4eAvVzgCNv3t8aMLWc3Pm4hphEh3xNhMMCK0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T13:34:45Z"
    mac: ENC[AES256_GCM,data:Ybp73c+DzrOMVdZOK+u1AB8hf0l75aYh0k0UX370VTf7CkJL7kbx2Atbgi+4XCr0A3q7YcAE4a+5QkoyGtBd8peySqLGOmgzhswY5AB3nTDOmDg4oEWuX14uz3trgprXxVnfcv7iG+OIgs6+k3QFMfppmI2t56Edg9wKId68DDM=,iv:wrkRxvAgr743prz8N56dGfWLxhwPtpsPXIg/r4j+aZ8=,tag:EOUpjqdWS/fQe8azPsaDkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
