apiVersion: v1
kind: Secret
metadata:
    name: ai-service-secret
    namespace: yetbota
    labels:
        app.kubernetes.io/name: ai-service
        app.kubernetes.io/part-of: yetbota
type: Opaque
stringData:
    GEMINI__API_KEY: ENC[AES256_GCM,data:rK/LPHy+HhAPcBsyeA+LhRA/o2A9I2DfQVcgbwBJEnvSyzcBz69e,iv:/UYMYNfB6FFmryaATG3DJVgRCHRT6VAFcudT91wv0WE=,tag:9l1TQzzqjg+0AoOQDOikSg==,type:str]
    WEAVIATE__API_KEY: ENC[AES256_GCM,data:JUfFJbzP2N6Kq4GA1Ta5MSk1tZkVPEgMxoSu4LlPfqd2jUgjNFtdsQw+qw==,iv:SnKTIEorlfMBXWOQiPdL0UqJh8D5wzUnbBNM01VSLPQ=,tag:6jh6hDJ8+XcWilQ8d452Eg==,type:str]
    NEO4J__PASSWORD: ENC[AES256_GCM,data:qaaY0bYBbYRG,iv:g/8jJTbiJFvTtr75nBYSc5pFWvRGut5QwhtOE+3m7vw=,tag:YElXZM/VGXXTnSTJTQddGw==,type:str]
    RABBITMQ__URI: ENC[AES256_GCM,data:1qRR8xdyDcw/FVZrIOBN9u3tB+CotS0jCDwKlF4jKm7y+qon74Kwj7aomUdfjVCi8vrmbfZqqQsb9ga2RQ==,iv:4/UrM3fDj9op5H1k7KqIYp+Lg5ZRQxrAZBh5lQyJcpY=,tag:vdovhCaGHcGbYSfAyZMWUA==,type:str]
sops:
    age:
        - recipient: age1aaplqegrnem7x5k89rtn2mfrajkjkapf0lamfw6fdjk9ru4e65cs7qnq7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c2pqb2tiYUpkRTJEek8r
            eDFpczNvTnU0dUx3YXNZNU1qUUp3QitiWlRJClY1U2N1SitlWUsxU1lNQ3NuTUJQ
            THRsdGxEcVNsaXc2Z1RWZk1pU1FpZmcKLS0tIEZLdnBncGNoZ1B2QnlHdEc0WVhr
            RnZIZjhBdTdjcmZKNkloU25aNFNYc2sKb/PpatUKCNqSeNcX+veclQruvNyYcE6P
            +dtm8pe7KlhohYxzBfLU/Kipe1k+Das+wkzdRH2DGBKNyfFdFVGe/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T11:18:24Z"
    mac: ENC[AES256_GCM,data:VF8n8pao2il8XG2AQ6En7+UnC4VR+zfPTiQbuhm7NOiI22RIKWxBnGOetfR7nPBQO8lb+yAbfp2ysXttfLx1QyRkFGP3LWOcGiCdBIydkLDSemQ7mPeAFJ/tbnkjWKJj0TVPSVSEPTbcFu+I0PBZZxkXXtiNlVI6/kSKpIenGy0=,iv:d8ciNuGKgNg606BlOpnEgryPECPx+xir2DWxGFOTEtY=,tag:P++BaXelrhcrAbJ9/geE8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
