apiVersion: v1
kind: Secret
metadata:
    name: ai-service-secret
    namespace: yetbota
    labels:
        app.kubernetes.io/name: ai-service
        app.kubernetes.io/part-of: yetbota
type: Opaque
stringData:
    GEMINI__API_KEY: ENC[AES256_GCM,data:fyGrluSWLIFgbXcPkCVYWxxvx+eIN7oKKysWSAtHNKt5gvzaSZcu,iv:38CgppPGpZsW0GCUY/wkwnIDHKAltUs2SoL80W9VUII=,tag:C+bxsSg1r8j14yRgaOC4mA==,type:str]
    WEAVIATE__API_KEY: ENC[AES256_GCM,data:iSRT8N5pfV+SIYKBRYYMK2P6+bpKJ4T2PB5C/g6gMxRRPyBfaw08UNp8i+9eP4kYUB6NlelgOEh82JV1cQBOWNdTGiwcjkZdyl+cL61nLallohpsCt31sA==,iv:YcVi0y4a35eUPOL7UpV8PZlr93i361QCYO3ihZDWlHk=,tag:POYC7ygTCr+jpxWGY6WjQA==,type:str]
    NEO4J__PASSWORD: ENC[AES256_GCM,data:Pi6/ZE9Oh3vK76iWX3GgN2ctgucyyPTvr6nBU83y7EFnNRX5kaqLrrExhA==,iv:RnhhfHGqGfZM6ZY5o489ATFgCdIXtESbS47UZUbixXs=,tag:27dH5lcYk2SEpFF04aideQ==,type:str]
    REDIS__URL: ENC[AES256_GCM,data:3Q+RbBWFqybOLInM/v6baA+1iwxGeoausO5ymE7+9lCqYMsJNbx9VhnmYBIdrYe+u4SRDwASr5GBxE4l/wd2,iv:YNN8dPvlUyCbZuCeFkWN8T5aKdAyHOmUMXiMnkFcBWI=,tag:JRQkvcxUmS8clkUvlQdeBg==,type:str]
sops:
    age:
        - recipient: age1aaplqegrnem7x5k89rtn2mfrajkjkapf0lamfw6fdjk9ru4e65cs7qnq7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTVd4cXFnVE04YXNucFN2
            V2I2NjNuczdkdk4rNjVXSUx4Uk9Hc1Z6eGtRCnk0UTM5WGIwOG55bm1ZRDY1NElz
            VTJ6dHJCMzFaVGV2a0h1S0lOdm1OTzAKLS0tIEdWZFBldEl3NXU4RTRyWXpNZERy
            cDVTRjErRWFLalpyd0h4LzZCUzJOR1EKh+UDKXfo/SnbLh5+fciGAsDfqYHdAzr2
            cjoZjTLNn3ZnAuo96m2ADk50dfhyew1vkSXkm/3K4XyvhnLjvVIMjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T06:05:32Z"
    mac: ENC[AES256_GCM,data:55VBe4bfBrlTmXZKXVqYr/Q1sTWDO9PTlnM6P/AOJvyxHcpjOTcOnTYk15V+FLdUgOIPNQFFcn8+cNISdagBkeA+4Lp82yt4s796UTOUuUoTb8VueXeAnHK4N9hxy+233FAp84G8IHNpycYUtp2yH53uK4a9R6XgWXAYcWHjZmU=,iv:tkZbN04jdAhSAM+66FVdlDLERbQ5jyZ9EqcSY27iL0I=,tag:nVQpkZ2pa9GtiIoAQidqTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
