services:
  redis:
    image: redis:7.4
    container_name: yetbota-redis
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${redisPassword}",
      ]
    ports:
      - "${redisPort}:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${redisPassword}

  db:
    image: postgis/postgis:13-3.4
    container_name: yetbota-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${postgresUser} -d ${postgresDB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${postgresPort}:5432"
    environment:
      POSTGRES_USER: ${postgresUser}
      POSTGRES_PASSWORD: ${postgresPassword}
      POSTGRES_DB: ${postgresDB}

  neo4j:
    image: neo4j:5
    container_name: yetbota-neo4j
    ports:
      - "${neo4jHttpPort}:7474"
      - "${neo4jBoltPort}:7687"
    environment:
      NEO4J_AUTH: ${neo4jUsername}/${neo4jPassword}
    volumes:
      - neo4j_data:/data

  temporal:
    image: temporalio/auto-setup:latest
    container_name: yetbota-temporal
    ports:
      - "${temporalGrpcPort}:7233"
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=${postgresMasterUser}
      - POSTGRES_PWD=${postgresMasterPassword}
      - POSTGRES_SEEDS=db
      - SKIP_DB_CREATE=false
      - SKIP_DEFAULT_NAMESPACE_CREATION=false
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - temporal_data:/var/lib/temporal

  temporal-ui:
    image: temporalio/ui:latest
    container_name: yetbota-temporal-ui
    ports:
      - "8233:8080"
    environment:
      - TEMPORAL_ADDRESS=yetbota-temporal:7233
    depends_on:
      - temporal

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  neo4j_data:
    driver: local
  temporal_data:
    driver: local
