apiVersion: v1
kind: Secret
metadata:
    name: content-service-secret
    namespace: yetbota
    labels:
        app.kubernetes.io/name: content-service
        app.kubernetes.io/part-of: yetbota
type: Opaque
stringData:
    debug: ENC[AES256_GCM,data:L7Rg6A==,iv:0jzTv+0eiuh131mJ/wbJWwxG080K3Lz9sD76NoqV2Vw=,tag:UVc/fWDzSEHrL6E/0MfKJQ==,type:str]
    corsHosts: ENC[AES256_GCM,data:f3rpFdZcQfNh,iv:KsyAzl6nG/3ZkseEMCZbpJyXWzDwVlVUrt6VQ9pOYq4=,tag:3pxRGd5IHKfPfrbTUn0S/g==,type:str]
    jwtAccessTokenSecret: ENC[AES256_GCM,data:FoCY6EczzCY5Xa27vZGUqSEEk9GBxq95IWs9G1oo3h6FBTL2WqtgvIo0TQ==,iv:7h+w6h0AnYkMliGlNoQolao3NgSIUb61P9XrFcMA6hY=,tag:I1qH7T0lA/LJEUjBwH5B7g==,type:str]
    jwtAccessTokenExpiration: ENC[AES256_GCM,data:VFkb,iv:iabmbCKrPSklPIC2ihS5ZVnifS/8HGB6qRY1ewMZ2F4=,tag:EtDl/nb0HpUc06XAMCovZQ==,type:str]
    jwtRefreshTokenSecret: ENC[AES256_GCM,data:tT+L58RbEVBCvpwQPT8YgVGm48xOmTPlfM5PXevOO1wz7WADQ+XYhNqBvQ==,iv:nJKyy9kHq0mDeP/rjGNu9Xd/9rG7VJHsY9XAfvHJ7z4=,tag:ZVPv9YiksfZ6zLe+U9CT+Q==,type:str]
    jwtRefreshTokenExpiration: ENC[AES256_GCM,data:8iJzogY9,iv:IWu6HSFrpb7E68N4IaNdCDjND6OxKto5sOtdBB2DotQ=,tag:fVp22L3Qwjk8Kqj+yVmivg==,type:str]
    postgresHost: ENC[AES256_GCM,data:tdBoDSOdoxKzAalOFbVxGUXCSCD/SPb3Gb7/imZHGrdKL3bNG79bqg==,iv:6mDLvLgTb/SFakd45W57VMTcLGEbLug2YxQrfWfGuvo=,tag:pXurmc5KmJw28agrApFmOw==,type:str]
    postgresPort: ENC[AES256_GCM,data:oAF4hQ==,iv:wsMDmPA1pxrOB2hW9Q8fkMIDlf/4b7PjMHgsc80DYyA=,tag:OmbH4zMbY8EIaabqumUPMA==,type:str]
    postgresDB: ENC[AES256_GCM,data:TRsevfYoVgijfA==,iv:ZbCsIJRYmOFfZWhpJJp42Xs/GY4zS3fjQxyOlnDCZLc=,tag:4jWn0D6hQuKayh/0Wf0rVQ==,type:str]
    postgresUser: ENC[AES256_GCM,data:/hVCXSuukw==,iv:lVIlj5mGnVvTLPFSM7R9lBeP4XCOmmqoDEmzzyGYVeE=,tag:GY+w5uc0zCpLzDCAMKTx4Q==,type:str]
    postgresPassword: ENC[AES256_GCM,data:/15zVGkxO1io+LQjQM7nxJfuga2k0vMji7D3iayOQM/aAgF1X5VJYeKhMA==,iv:+Tsdv6u4u0Ht/+SXJlZdnKDUZFtbGOi+E0XVQbv0Dj4=,tag:8KvajdyHGOnACv0Z2qOf8w==,type:str]
    redisAddress: ENC[AES256_GCM,data:y1MlXM6fCu4WNh3Lk917vW/klqc4b4f1w1SBvaW9/hAJqO0IWqoNiiKx,iv:MF8zTF8GAYrn7VCirQX3Ebj2kXuSvTSzecBG2KqgFX4=,tag:PNs1zcSKi2rceT0gslRciQ==,type:str]
    redisPassword: ENC[AES256_GCM,data:M5MzRQ1cpyIKevckIQ6ZuGs+4cTzg7Re8NwYzBkx,iv:KnGsYocvP+Sx/aoEnzMFYE74kB5uKHkRGVTAgkvGbjE=,tag:oVummWuH6f5X7YU/ge2m4A==,type:str]
    redisPoolTimeout: ENC[AES256_GCM,data:3k52,iv:7n7u4lL5ZeC3I1y7tHZnKI5OPRM+azFds8320NnNQUo=,tag:FEs0umU3Hb7hZyhPAFt3SQ==,type:str]
    redisIdleTimeout: ENC[AES256_GCM,data:3Bhutg==,iv:6i2WIzea7bIU+0gR/ol5FBTyIzyRkvRz6prregpcKrE=,tag:WkkcZ+od9LiL4IM5V9JKfg==,type:str]
    redisReadTimeout: ENC[AES256_GCM,data:ISg=,iv:mTM4NSfG38k7qnU16DQPnFy6sJOrUGxVuU4OmWed31Y=,tag:c0shmEFnliydol5kAi8YXw==,type:str]
    redisWriteTimeout: ENC[AES256_GCM,data:ZGo=,iv:Ap9P+rqZWlkR9NP/jA8A7ORBOua20kzZFBC0+r9ZF2E=,tag:LWioMwv0btxrV+dCZHeFzg==,type:str]
    otpTTL: ENC[AES256_GCM,data:73+f,iv:/uhC564iPXEKQ42eB0mavWYi89kYD/oTq5j48n1IGjI=,tag:sXw62XD3lZ8Fz5ZwzAUq6Q==,type:str]
    otpLockRequestTime: ENC[AES256_GCM,data:98c=,iv:Nb/eIsLeKFaOwjQZ5jo2DOkIkyOvuqmVuvLK1NWjh4s=,tag:nSVlZfBg0WDSj2k/8J3Sgg==,type:str]
    otpLockInvalidTime: ENC[AES256_GCM,data:SLRM,iv:CU+aCJ/eBCF/Ej952h3sGh/UHaW2NysqMzgB9Ku9vBQ=,tag:amwXJOehfo30krc1HYJYkw==,type:str]
    neo4jURI: ENC[AES256_GCM,data:U2ZbeC+uLGVUlz5QdVTIUhx/quiU/uRP5oFHaAZUYJ4qNrFhJSLirBlEdMGwnPwnmw==,iv:nskEg9usEQIRj2zL3QTwD1Ll69nWnuril+X8zU6XiqM=,tag:ZUUA85rz6uaZZQKRBg3rlQ==,type:str]
    neo4jUsername: ENC[AES256_GCM,data:4EX763s=,iv:lbxJTUHNyvWdcF6CVeGocX/8IMcQv18lX/bx4caJJ1Q=,tag:4f6efsM9rAmRKAZXumcJKA==,type:str]
    neo4jPassword: ENC[AES256_GCM,data:eoBkjD3judKoTVmEA7IdCDdrWH6139dbTH4Arfnu5vA7e1K07iNiiHectQ==,iv:alR94rzP5r0bdyUGR9gKzjTgTiOlFlavafq1vRCCJRA=,tag:a7npcd1xBSOpx1fBTLcJOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aaplqegrnem7x5k89rtn2mfrajkjkapf0lamfw6fdjk9ru4e65cs7qnq7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUTdSZE9CelJpNkg0YjBG
            MGNka3kweUQzRTA2eWprRUdWYXgyQkhVTFJRCjZpVTArblArbG5vcXdLY3IwMXFC
            cmNMUjFRbGF3NEh0VndmUEdlMlRETHMKLS0tIFliYnc5MHd0MmxIU250RHdIcFdp
            bkZ4Z3RKN3o1ZUZRTndHS2JlMGpXdTAKnV/btuyfbVJq0jFxKxWOjvL+1/cT9HIx
            IUPbKbB4E5OcIUg/hzAz85E3YEeCFFJJosInvCpXcMJIz/7jbxO6Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:20:54Z"
    mac: ENC[AES256_GCM,data:Q4wcZYhyk12G3333Gv3QqvL+rVwZmtIfNN9qIP6gzEKmNcQYoQ5LIhbDdqYEZ6JG87S4xGB7iLe8QeRRXELC5MSqRgU4jj9bMqP3u1hNNgR8fDVQ45beB9dI/7zt16qsel/1gGc2LoP0MxxOJKNHEMZAmBK6+rFhl13ownsFrR8=,iv:519MGuPlUlfbg6yXunugUiZGzNHK/yG3kahdoJ+7SUo=,tag:K5h/Nz7pxQzWApno19CAcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
