apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: yetbota
  labels:
    app.kubernetes.io/name: content-service
    app.kubernetes.io/part-of: yetbota
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: content-service
  ports:
    - name: grpc
      port: 9696
      targetPort: grpc
      protocol: TCP
    - name: rest
      port: 9966
      targetPort: rest
      protocol: TCP
