apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
  namespace: yetbota-infra
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: yetbota
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
