apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: yetbota-infra
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: yetbota
spec:
  selector:
    app.kubernetes.io/name: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: http
      protocol: TCP
    - name: bolt
      port: 7687
      targetPort: bolt
      protocol: TCP
