apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: content-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/beka-birhanu/yetbota.git
    targetRevision: HEAD
    path: infra/content-service
  destination:
    server: https://kubernetes.default.svc
    namespace: yetbota
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
