apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yetbota
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/beka-birhanu/yetbota.git
    targetRevision: HEAD
    path: infra/argocd/apps
    directory:
      exclude: root-app.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
