apiVersion: v1
kind: Secret
metadata:
    name: temporal-secret
    namespace: yetbota-infra
    labels:
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: yetbota
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:+g69PvCEaw==,iv:pcXAimYrIPKQwH8WQ/ne14bWEEWT8/a92UTABJ06CCM=,tag:2z66uyHza+y2/UGvjArVbA==,type:str]
    POSTGRES_PWD: ENC[AES256_GCM,data:nw8BqJ6p/Xk1QHOHKLNWm44e0MyrnlsMgMPvwathoNdCo52k+6pJ0Nt/2w==,iv:N03HDny8HGQdfipQ5ekx75jB2IfWTrvMWrPRd4+1z+E=,tag:6z0HzPVN4attg9J/38l78Q==,type:str]
sops:
    age:
        - recipient: age1aaplqegrnem7x5k89rtn2mfrajkjkapf0lamfw6fdjk9ru4e65cs7qnq7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS3NQaFdiMXQ3ZGIrTExv
            b0l4K0tjTmdUL1ZEcm1SUFhTZFdnWmxMRWdFCkpFQ1dOT3ZYRTFUMW92ZzR5T0hP
            V054a2J0Mkg5TGRuM2FlQzZLeVNjdkEKLS0tIHRpZDY2MkVRQUcwOVpSeDlFeVhQ
            U1VCa3dYZlUvbzR5dnJIMXI2RktnVncKUaZULDH6s4owU3fW2OeK5xi/cVSc26aO
            sqBe5g7eIkwpGFM+qzOD8j0it0IQ6Q2QclLZ95ZIEvKU74we9u0s0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T08:49:44Z"
    mac: ENC[AES256_GCM,data:9TwElnUJx7a0Yy6op4BibByovAAJiDFPiQ2ZQULfHpzjz+psZVFfB1jI2BIBsFlweg8OkLhXDiroY5eFeUIZdG5Ey4dfhXDYPHwjmr/fMuf3Z5loYHK8n8ioy3tuM4ZVAxujBN4dFb6Hf8SFoFeKUqVz+bBhjzcQuZMh0ag93Ns=,iv:RPROmx6rNTLmVSqZuIDYS/W8WwQPqOu7fkV2uOkTF4I=,tag:f3/HaExn7RZZ14ZbtQXI5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
