apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: temporal-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - temporal/secret.enc.yaml
