// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	Comments      string
	Photos        string
	PostPhotos    string
	PostVotes     string
	Posts         string
	UserSeenPosts string
}{
	Comments:      "comments",
	Photos:        "photos",
	PostPhotos:    "post_photos",
	PostVotes:     "post_votes",
	Posts:         "posts",
	UserSeenPosts: "user_seen_posts",
}
