// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// CommentVote is an object representing the database table.
type CommentVote struct {
	UserID    string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	CommentID string    `boil:"comment_id" json:"comment_id" toml:"comment_id" yaml:"comment_id"`
	VoteType  string    `boil:"vote_type" json:"vote_type" toml:"vote_type" yaml:"vote_type"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *commentVoteR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L commentVoteL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CommentVoteColumns = struct {
	UserID    string
	CommentID string
	VoteType  string
	CreatedAt string
}{
	UserID:    "user_id",
	CommentID: "comment_id",
	VoteType:  "vote_type",
	CreatedAt: "created_at",
}

var CommentVoteTableColumns = struct {
	UserID    string
	CommentID string
	VoteType  string
	CreatedAt string
}{
	UserID:    "comment_votes.user_id",
	CommentID: "comment_votes.comment_id",
	VoteType:  "comment_votes.vote_type",
	CreatedAt: "comment_votes.created_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var CommentVoteWhere = struct {
	UserID    whereHelperstring
	CommentID whereHelperstring
	VoteType  whereHelperstring
	CreatedAt whereHelpertime_Time
}{
	UserID:    whereHelperstring{field: "\"comment_votes\".\"user_id\""},
	CommentID: whereHelperstring{field: "\"comment_votes\".\"comment_id\""},
	VoteType:  whereHelperstring{field: "\"comment_votes\".\"vote_type\""},
	CreatedAt: whereHelpertime_Time{field: "\"comment_votes\".\"created_at\""},
}

// CommentVoteRels is where relationship names are stored.
var CommentVoteRels = struct {
	Comment string
}{
	Comment: "Comment",
}

// commentVoteR is where relationships are stored.
type commentVoteR struct {
	Comment *Comment `boil:"Comment" json:"Comment" toml:"Comment" yaml:"Comment"`
}

// NewStruct creates a new relationship struct
func (*commentVoteR) NewStruct() *commentVoteR {
	return &commentVoteR{}
}

func (o *CommentVote) GetComment() *Comment {
	if o == nil {
		return nil
	}

	return o.R.GetComment()
}

func (r *commentVoteR) GetComment() *Comment {
	if r == nil {
		return nil
	}

	return r.Comment
}

// commentVoteL is where Load methods for each relationship are stored.
type commentVoteL struct{}

var (
	commentVoteAllColumns            = []string{"user_id", "comment_id", "vote_type", "created_at"}
	commentVoteColumnsWithoutDefault = []string{"user_id", "comment_id", "vote_type"}
	commentVoteColumnsWithDefault    = []string{"created_at"}
	commentVotePrimaryKeyColumns     = []string{"user_id", "comment_id"}
	commentVoteGeneratedColumns      = []string{}
)

type (
	// CommentVoteSlice is an alias for a slice of pointers to CommentVote.
	// This should almost always be used instead of []CommentVote.
	CommentVoteSlice []*CommentVote
	// CommentVoteHook is the signature for custom CommentVote hook methods
	CommentVoteHook func(context.Context, boil.ContextExecutor, *CommentVote) error

	commentVoteQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	commentVoteType                 = reflect.TypeOf(&CommentVote{})
	commentVoteMapping              = queries.MakeStructMapping(commentVoteType)
	commentVotePrimaryKeyMapping, _ = queries.BindMapping(commentVoteType, commentVoteMapping, commentVotePrimaryKeyColumns)
	commentVoteInsertCacheMut       sync.RWMutex
	commentVoteInsertCache          = make(map[string]insertCache)
	commentVoteUpdateCacheMut       sync.RWMutex
	commentVoteUpdateCache          = make(map[string]updateCache)
	commentVoteUpsertCacheMut       sync.RWMutex
	commentVoteUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var commentVoteAfterSelectMu sync.Mutex
var commentVoteAfterSelectHooks []CommentVoteHook

var commentVoteBeforeInsertMu sync.Mutex
var commentVoteBeforeInsertHooks []CommentVoteHook
var commentVoteAfterInsertMu sync.Mutex
var commentVoteAfterInsertHooks []CommentVoteHook

var commentVoteBeforeUpdateMu sync.Mutex
var commentVoteBeforeUpdateHooks []CommentVoteHook
var commentVoteAfterUpdateMu sync.Mutex
var commentVoteAfterUpdateHooks []CommentVoteHook

var commentVoteBeforeDeleteMu sync.Mutex
var commentVoteBeforeDeleteHooks []CommentVoteHook
var commentVoteAfterDeleteMu sync.Mutex
var commentVoteAfterDeleteHooks []CommentVoteHook

var commentVoteBeforeUpsertMu sync.Mutex
var commentVoteBeforeUpsertHooks []CommentVoteHook
var commentVoteAfterUpsertMu sync.Mutex
var commentVoteAfterUpsertHooks []CommentVoteHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CommentVote) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commentVoteAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CommentVote) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commentVoteBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CommentVote) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commentVoteAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CommentVote) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commentVoteBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CommentVote) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commentVoteAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CommentVote) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commentVoteBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CommentVote) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commentVoteAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CommentVote) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commentVoteBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CommentVote) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range commentVoteAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCommentVoteHook registers your hook function for all future operations.
func AddCommentVoteHook(hookPoint boil.HookPoint, commentVoteHook CommentVoteHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		commentVoteAfterSelectMu.Lock()
		commentVoteAfterSelectHooks = append(commentVoteAfterSelectHooks, commentVoteHook)
		commentVoteAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		commentVoteBeforeInsertMu.Lock()
		commentVoteBeforeInsertHooks = append(commentVoteBeforeInsertHooks, commentVoteHook)
		commentVoteBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		commentVoteAfterInsertMu.Lock()
		commentVoteAfterInsertHooks = append(commentVoteAfterInsertHooks, commentVoteHook)
		commentVoteAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		commentVoteBeforeUpdateMu.Lock()
		commentVoteBeforeUpdateHooks = append(commentVoteBeforeUpdateHooks, commentVoteHook)
		commentVoteBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		commentVoteAfterUpdateMu.Lock()
		commentVoteAfterUpdateHooks = append(commentVoteAfterUpdateHooks, commentVoteHook)
		commentVoteAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		commentVoteBeforeDeleteMu.Lock()
		commentVoteBeforeDeleteHooks = append(commentVoteBeforeDeleteHooks, commentVoteHook)
		commentVoteBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		commentVoteAfterDeleteMu.Lock()
		commentVoteAfterDeleteHooks = append(commentVoteAfterDeleteHooks, commentVoteHook)
		commentVoteAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		commentVoteBeforeUpsertMu.Lock()
		commentVoteBeforeUpsertHooks = append(commentVoteBeforeUpsertHooks, commentVoteHook)
		commentVoteBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		commentVoteAfterUpsertMu.Lock()
		commentVoteAfterUpsertHooks = append(commentVoteAfterUpsertHooks, commentVoteHook)
		commentVoteAfterUpsertMu.Unlock()
	}
}

// One returns a single commentVote record from the query.
func (q commentVoteQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CommentVote, error) {
	o := &CommentVote{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for comment_votes")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all CommentVote records from the query.
func (q commentVoteQuery) All(ctx context.Context, exec boil.ContextExecutor) (CommentVoteSlice, error) {
	var o []*CommentVote

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to CommentVote slice")
	}

	if len(commentVoteAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all CommentVote records in the query.
func (q commentVoteQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count comment_votes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q commentVoteQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if comment_votes exists")
	}

	return count > 0, nil
}

// Comment pointed to by the foreign key.
func (o *CommentVote) Comment(mods ...qm.QueryMod) commentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CommentID),
	}

	queryMods = append(queryMods, mods...)

	return Comments(queryMods...)
}

// LoadComment allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (commentVoteL) LoadComment(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCommentVote any, mods queries.Applicator) error {
	var slice []*CommentVote
	var object *CommentVote

	if singular {
		var ok bool
		object, ok = maybeCommentVote.(*CommentVote)
		if !ok {
			object = new(CommentVote)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCommentVote)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCommentVote))
			}
		}
	} else {
		s, ok := maybeCommentVote.(*[]*CommentVote)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCommentVote)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCommentVote))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &commentVoteR{}
		}
		args[object.CommentID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &commentVoteR{}
			}

			args[obj.CommentID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`comments`),
		qm.WhereIn(`comments.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Comment")
	}

	var resultSlice []*Comment
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Comment")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for comments")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for comments")
	}

	if len(commentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Comment = foreign
		if foreign.R == nil {
			foreign.R = &commentR{}
		}
		foreign.R.CommentVotes = append(foreign.R.CommentVotes, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CommentID == foreign.ID {
				local.R.Comment = foreign
				if foreign.R == nil {
					foreign.R = &commentR{}
				}
				foreign.R.CommentVotes = append(foreign.R.CommentVotes, local)
				break
			}
		}
	}

	return nil
}

// SetComment of the commentVote to the related item.
// Sets o.R.Comment to related.
// Adds o to related.R.CommentVotes.
func (o *CommentVote) SetComment(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Comment) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"comment_votes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"comment_id"}),
		strmangle.WhereClause("\"", "\"", 2, commentVotePrimaryKeyColumns),
	)
	values := []any{related.ID, o.UserID, o.CommentID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CommentID = related.ID
	if o.R == nil {
		o.R = &commentVoteR{
			Comment: related,
		}
	} else {
		o.R.Comment = related
	}

	if related.R == nil {
		related.R = &commentR{
			CommentVotes: CommentVoteSlice{o},
		}
	} else {
		related.R.CommentVotes = append(related.R.CommentVotes, o)
	}

	return nil
}

// CommentVotes retrieves all the records using an executor.
func CommentVotes(mods ...qm.QueryMod) commentVoteQuery {
	mods = append(mods, qm.From("\"comment_votes\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"comment_votes\".*"})
	}

	return commentVoteQuery{q}
}

// FindCommentVote retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCommentVote(ctx context.Context, exec boil.ContextExecutor, userID string, commentID string, selectCols ...string) (*CommentVote, error) {
	commentVoteObj := &CommentVote{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"comment_votes\" where \"user_id\"=$1 AND \"comment_id\"=$2", sel,
	)

	q := queries.Raw(query, userID, commentID)

	err := q.Bind(ctx, exec, commentVoteObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from comment_votes")
	}

	if err = commentVoteObj.doAfterSelectHooks(ctx, exec); err != nil {
		return commentVoteObj, err
	}

	return commentVoteObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CommentVote) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no comment_votes provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(commentVoteColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	commentVoteInsertCacheMut.RLock()
	cache, cached := commentVoteInsertCache[key]
	commentVoteInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			commentVoteAllColumns,
			commentVoteColumnsWithDefault,
			commentVoteColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(commentVoteType, commentVoteMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(commentVoteType, commentVoteMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"comment_votes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"comment_votes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into comment_votes")
	}

	if !cached {
		commentVoteInsertCacheMut.Lock()
		commentVoteInsertCache[key] = cache
		commentVoteInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the CommentVote.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CommentVote) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	commentVoteUpdateCacheMut.RLock()
	cache, cached := commentVoteUpdateCache[key]
	commentVoteUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			commentVoteAllColumns,
			commentVotePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update comment_votes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"comment_votes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, commentVotePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(commentVoteType, commentVoteMapping, append(wl, commentVotePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update comment_votes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for comment_votes")
	}

	if !cached {
		commentVoteUpdateCacheMut.Lock()
		commentVoteUpdateCache[key] = cache
		commentVoteUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q commentVoteQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for comment_votes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for comment_votes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CommentVoteSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commentVotePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"comment_votes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, commentVotePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in commentVote slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all commentVote")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CommentVote) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no comment_votes provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(commentVoteColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	commentVoteUpsertCacheMut.RLock()
	cache, cached := commentVoteUpsertCache[key]
	commentVoteUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			commentVoteAllColumns,
			commentVoteColumnsWithDefault,
			commentVoteColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			commentVoteAllColumns,
			commentVotePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert comment_votes, could not build update column list")
		}

		ret := strmangle.SetComplement(commentVoteAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(commentVotePrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert comment_votes, could not build conflict column list")
			}

			conflict = make([]string, len(commentVotePrimaryKeyColumns))
			copy(conflict, commentVotePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"comment_votes\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(commentVoteType, commentVoteMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(commentVoteType, commentVoteMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert comment_votes")
	}

	if !cached {
		commentVoteUpsertCacheMut.Lock()
		commentVoteUpsertCache[key] = cache
		commentVoteUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single CommentVote record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CommentVote) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no CommentVote provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), commentVotePrimaryKeyMapping)
	sql := "DELETE FROM \"comment_votes\" WHERE \"user_id\"=$1 AND \"comment_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from comment_votes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for comment_votes")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q commentVoteQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no commentVoteQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from comment_votes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for comment_votes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CommentVoteSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(commentVoteBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commentVotePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"comment_votes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, commentVotePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from commentVote slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for comment_votes")
	}

	if len(commentVoteAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CommentVote) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCommentVote(ctx, exec, o.UserID, o.CommentID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CommentVoteSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CommentVoteSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), commentVotePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"comment_votes\".* FROM \"comment_votes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, commentVotePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in CommentVoteSlice")
	}

	*o = slice

	return nil
}

// CommentVoteExists checks if the CommentVote row exists.
func CommentVoteExists(ctx context.Context, exec boil.ContextExecutor, userID string, commentID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"comment_votes\" where \"user_id\"=$1 AND \"comment_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID, commentID)
	}
	row := exec.QueryRowContext(ctx, sql, userID, commentID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if comment_votes exists")
	}

	return exists, nil
}

// Exists checks if the CommentVote row exists.
func (o *CommentVote) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CommentVoteExists(ctx, exec, o.UserID, o.CommentID)
}
