// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PostPhoto is an object representing the database table.
type PostPhoto struct {
	ID       string `boil:"id" json:"id" toml:"id" yaml:"id"`
	PostID   string `boil:"post_id" json:"post_id" toml:"post_id" yaml:"post_id"`
	PhotoID  string `boil:"photo_id" json:"photo_id" toml:"photo_id" yaml:"photo_id"`
	Position int    `boil:"position" json:"position" toml:"position" yaml:"position"`

	R *postPhotoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L postPhotoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PostPhotoColumns = struct {
	ID       string
	PostID   string
	PhotoID  string
	Position string
}{
	ID:       "id",
	PostID:   "post_id",
	PhotoID:  "photo_id",
	Position: "position",
}

var PostPhotoTableColumns = struct {
	ID       string
	PostID   string
	PhotoID  string
	Position string
}{
	ID:       "post_photos.id",
	PostID:   "post_photos.post_id",
	PhotoID:  "post_photos.photo_id",
	Position: "post_photos.position",
}

// Generated where

var PostPhotoWhere = struct {
	ID       whereHelperstring
	PostID   whereHelperstring
	PhotoID  whereHelperstring
	Position whereHelperint
}{
	ID:       whereHelperstring{field: "\"post_photos\".\"id\""},
	PostID:   whereHelperstring{field: "\"post_photos\".\"post_id\""},
	PhotoID:  whereHelperstring{field: "\"post_photos\".\"photo_id\""},
	Position: whereHelperint{field: "\"post_photos\".\"position\""},
}

// PostPhotoRels is where relationship names are stored.
var PostPhotoRels = struct {
	Photo string
	Post  string
}{
	Photo: "Photo",
	Post:  "Post",
}

// postPhotoR is where relationships are stored.
type postPhotoR struct {
	Photo *Photo `boil:"Photo" json:"Photo" toml:"Photo" yaml:"Photo"`
	Post  *Post  `boil:"Post" json:"Post" toml:"Post" yaml:"Post"`
}

// NewStruct creates a new relationship struct
func (*postPhotoR) NewStruct() *postPhotoR {
	return &postPhotoR{}
}

func (o *PostPhoto) GetPhoto() *Photo {
	if o == nil {
		return nil
	}

	return o.R.GetPhoto()
}

func (r *postPhotoR) GetPhoto() *Photo {
	if r == nil {
		return nil
	}

	return r.Photo
}

func (o *PostPhoto) GetPost() *Post {
	if o == nil {
		return nil
	}

	return o.R.GetPost()
}

func (r *postPhotoR) GetPost() *Post {
	if r == nil {
		return nil
	}

	return r.Post
}

// postPhotoL is where Load methods for each relationship are stored.
type postPhotoL struct{}

var (
	postPhotoAllColumns            = []string{"id", "post_id", "photo_id", "position"}
	postPhotoColumnsWithoutDefault = []string{"post_id", "photo_id", "position"}
	postPhotoColumnsWithDefault    = []string{"id"}
	postPhotoPrimaryKeyColumns     = []string{"id"}
	postPhotoGeneratedColumns      = []string{}
)

type (
	// PostPhotoSlice is an alias for a slice of pointers to PostPhoto.
	// This should almost always be used instead of []PostPhoto.
	PostPhotoSlice []*PostPhoto
	// PostPhotoHook is the signature for custom PostPhoto hook methods
	PostPhotoHook func(context.Context, boil.ContextExecutor, *PostPhoto) error

	postPhotoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	postPhotoType                 = reflect.TypeOf(&PostPhoto{})
	postPhotoMapping              = queries.MakeStructMapping(postPhotoType)
	postPhotoPrimaryKeyMapping, _ = queries.BindMapping(postPhotoType, postPhotoMapping, postPhotoPrimaryKeyColumns)
	postPhotoInsertCacheMut       sync.RWMutex
	postPhotoInsertCache          = make(map[string]insertCache)
	postPhotoUpdateCacheMut       sync.RWMutex
	postPhotoUpdateCache          = make(map[string]updateCache)
	postPhotoUpsertCacheMut       sync.RWMutex
	postPhotoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var postPhotoAfterSelectMu sync.Mutex
var postPhotoAfterSelectHooks []PostPhotoHook

var postPhotoBeforeInsertMu sync.Mutex
var postPhotoBeforeInsertHooks []PostPhotoHook
var postPhotoAfterInsertMu sync.Mutex
var postPhotoAfterInsertHooks []PostPhotoHook

var postPhotoBeforeUpdateMu sync.Mutex
var postPhotoBeforeUpdateHooks []PostPhotoHook
var postPhotoAfterUpdateMu sync.Mutex
var postPhotoAfterUpdateHooks []PostPhotoHook

var postPhotoBeforeDeleteMu sync.Mutex
var postPhotoBeforeDeleteHooks []PostPhotoHook
var postPhotoAfterDeleteMu sync.Mutex
var postPhotoAfterDeleteHooks []PostPhotoHook

var postPhotoBeforeUpsertMu sync.Mutex
var postPhotoBeforeUpsertHooks []PostPhotoHook
var postPhotoAfterUpsertMu sync.Mutex
var postPhotoAfterUpsertHooks []PostPhotoHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PostPhoto) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postPhotoAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PostPhoto) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postPhotoBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PostPhoto) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postPhotoAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PostPhoto) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postPhotoBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PostPhoto) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postPhotoAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PostPhoto) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postPhotoBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PostPhoto) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postPhotoAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PostPhoto) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postPhotoBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PostPhoto) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postPhotoAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPostPhotoHook registers your hook function for all future operations.
func AddPostPhotoHook(hookPoint boil.HookPoint, postPhotoHook PostPhotoHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		postPhotoAfterSelectMu.Lock()
		postPhotoAfterSelectHooks = append(postPhotoAfterSelectHooks, postPhotoHook)
		postPhotoAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		postPhotoBeforeInsertMu.Lock()
		postPhotoBeforeInsertHooks = append(postPhotoBeforeInsertHooks, postPhotoHook)
		postPhotoBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		postPhotoAfterInsertMu.Lock()
		postPhotoAfterInsertHooks = append(postPhotoAfterInsertHooks, postPhotoHook)
		postPhotoAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		postPhotoBeforeUpdateMu.Lock()
		postPhotoBeforeUpdateHooks = append(postPhotoBeforeUpdateHooks, postPhotoHook)
		postPhotoBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		postPhotoAfterUpdateMu.Lock()
		postPhotoAfterUpdateHooks = append(postPhotoAfterUpdateHooks, postPhotoHook)
		postPhotoAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		postPhotoBeforeDeleteMu.Lock()
		postPhotoBeforeDeleteHooks = append(postPhotoBeforeDeleteHooks, postPhotoHook)
		postPhotoBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		postPhotoAfterDeleteMu.Lock()
		postPhotoAfterDeleteHooks = append(postPhotoAfterDeleteHooks, postPhotoHook)
		postPhotoAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		postPhotoBeforeUpsertMu.Lock()
		postPhotoBeforeUpsertHooks = append(postPhotoBeforeUpsertHooks, postPhotoHook)
		postPhotoBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		postPhotoAfterUpsertMu.Lock()
		postPhotoAfterUpsertHooks = append(postPhotoAfterUpsertHooks, postPhotoHook)
		postPhotoAfterUpsertMu.Unlock()
	}
}

// One returns a single postPhoto record from the query.
func (q postPhotoQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PostPhoto, error) {
	o := &PostPhoto{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for post_photos")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PostPhoto records from the query.
func (q postPhotoQuery) All(ctx context.Context, exec boil.ContextExecutor) (PostPhotoSlice, error) {
	var o []*PostPhoto

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to PostPhoto slice")
	}

	if len(postPhotoAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PostPhoto records in the query.
func (q postPhotoQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count post_photos rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q postPhotoQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if post_photos exists")
	}

	return count > 0, nil
}

// Photo pointed to by the foreign key.
func (o *PostPhoto) Photo(mods ...qm.QueryMod) photoQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PhotoID),
	}

	queryMods = append(queryMods, mods...)

	return Photos(queryMods...)
}

// Post pointed to by the foreign key.
func (o *PostPhoto) Post(mods ...qm.QueryMod) postQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PostID),
	}

	queryMods = append(queryMods, mods...)

	return Posts(queryMods...)
}

// LoadPhoto allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (postPhotoL) LoadPhoto(ctx context.Context, e boil.ContextExecutor, singular bool, maybePostPhoto any, mods queries.Applicator) error {
	var slice []*PostPhoto
	var object *PostPhoto

	if singular {
		var ok bool
		object, ok = maybePostPhoto.(*PostPhoto)
		if !ok {
			object = new(PostPhoto)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePostPhoto)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePostPhoto))
			}
		}
	} else {
		s, ok := maybePostPhoto.(*[]*PostPhoto)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePostPhoto)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePostPhoto))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &postPhotoR{}
		}
		args[object.PhotoID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &postPhotoR{}
			}

			args[obj.PhotoID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`photos`),
		qm.WhereIn(`photos.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Photo")
	}

	var resultSlice []*Photo
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Photo")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for photos")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for photos")
	}

	if len(photoAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Photo = foreign
		if foreign.R == nil {
			foreign.R = &photoR{}
		}
		foreign.R.PostPhotos = append(foreign.R.PostPhotos, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PhotoID == foreign.ID {
				local.R.Photo = foreign
				if foreign.R == nil {
					foreign.R = &photoR{}
				}
				foreign.R.PostPhotos = append(foreign.R.PostPhotos, local)
				break
			}
		}
	}

	return nil
}

// LoadPost allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (postPhotoL) LoadPost(ctx context.Context, e boil.ContextExecutor, singular bool, maybePostPhoto any, mods queries.Applicator) error {
	var slice []*PostPhoto
	var object *PostPhoto

	if singular {
		var ok bool
		object, ok = maybePostPhoto.(*PostPhoto)
		if !ok {
			object = new(PostPhoto)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePostPhoto)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePostPhoto))
			}
		}
	} else {
		s, ok := maybePostPhoto.(*[]*PostPhoto)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePostPhoto)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePostPhoto))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &postPhotoR{}
		}
		args[object.PostID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &postPhotoR{}
			}

			args[obj.PostID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`posts`),
		qm.WhereIn(`posts.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Post")
	}

	var resultSlice []*Post
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Post")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for posts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for posts")
	}

	if len(postAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Post = foreign
		if foreign.R == nil {
			foreign.R = &postR{}
		}
		foreign.R.PostPhotos = append(foreign.R.PostPhotos, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PostID == foreign.ID {
				local.R.Post = foreign
				if foreign.R == nil {
					foreign.R = &postR{}
				}
				foreign.R.PostPhotos = append(foreign.R.PostPhotos, local)
				break
			}
		}
	}

	return nil
}

// SetPhoto of the postPhoto to the related item.
// Sets o.R.Photo to related.
// Adds o to related.R.PostPhotos.
func (o *PostPhoto) SetPhoto(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Photo) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"post_photos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"photo_id"}),
		strmangle.WhereClause("\"", "\"", 2, postPhotoPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PhotoID = related.ID
	if o.R == nil {
		o.R = &postPhotoR{
			Photo: related,
		}
	} else {
		o.R.Photo = related
	}

	if related.R == nil {
		related.R = &photoR{
			PostPhotos: PostPhotoSlice{o},
		}
	} else {
		related.R.PostPhotos = append(related.R.PostPhotos, o)
	}

	return nil
}

// SetPost of the postPhoto to the related item.
// Sets o.R.Post to related.
// Adds o to related.R.PostPhotos.
func (o *PostPhoto) SetPost(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Post) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"post_photos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"post_id"}),
		strmangle.WhereClause("\"", "\"", 2, postPhotoPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PostID = related.ID
	if o.R == nil {
		o.R = &postPhotoR{
			Post: related,
		}
	} else {
		o.R.Post = related
	}

	if related.R == nil {
		related.R = &postR{
			PostPhotos: PostPhotoSlice{o},
		}
	} else {
		related.R.PostPhotos = append(related.R.PostPhotos, o)
	}

	return nil
}

// PostPhotos retrieves all the records using an executor.
func PostPhotos(mods ...qm.QueryMod) postPhotoQuery {
	mods = append(mods, qm.From("\"post_photos\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"post_photos\".*"})
	}

	return postPhotoQuery{q}
}

// FindPostPhoto retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPostPhoto(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*PostPhoto, error) {
	postPhotoObj := &PostPhoto{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"post_photos\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, postPhotoObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from post_photos")
	}

	if err = postPhotoObj.doAfterSelectHooks(ctx, exec); err != nil {
		return postPhotoObj, err
	}

	return postPhotoObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PostPhoto) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no post_photos provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(postPhotoColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	postPhotoInsertCacheMut.RLock()
	cache, cached := postPhotoInsertCache[key]
	postPhotoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			postPhotoAllColumns,
			postPhotoColumnsWithDefault,
			postPhotoColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(postPhotoType, postPhotoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(postPhotoType, postPhotoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"post_photos\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"post_photos\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into post_photos")
	}

	if !cached {
		postPhotoInsertCacheMut.Lock()
		postPhotoInsertCache[key] = cache
		postPhotoInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PostPhoto.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PostPhoto) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	postPhotoUpdateCacheMut.RLock()
	cache, cached := postPhotoUpdateCache[key]
	postPhotoUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			postPhotoAllColumns,
			postPhotoPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update post_photos, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"post_photos\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, postPhotoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(postPhotoType, postPhotoMapping, append(wl, postPhotoPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update post_photos row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for post_photos")
	}

	if !cached {
		postPhotoUpdateCacheMut.Lock()
		postPhotoUpdateCache[key] = cache
		postPhotoUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q postPhotoQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for post_photos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for post_photos")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PostPhotoSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), postPhotoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"post_photos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, postPhotoPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in postPhoto slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all postPhoto")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PostPhoto) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no post_photos provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(postPhotoColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	postPhotoUpsertCacheMut.RLock()
	cache, cached := postPhotoUpsertCache[key]
	postPhotoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			postPhotoAllColumns,
			postPhotoColumnsWithDefault,
			postPhotoColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			postPhotoAllColumns,
			postPhotoPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert post_photos, could not build update column list")
		}

		ret := strmangle.SetComplement(postPhotoAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(postPhotoPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert post_photos, could not build conflict column list")
			}

			conflict = make([]string, len(postPhotoPrimaryKeyColumns))
			copy(conflict, postPhotoPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"post_photos\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(postPhotoType, postPhotoMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(postPhotoType, postPhotoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert post_photos")
	}

	if !cached {
		postPhotoUpsertCacheMut.Lock()
		postPhotoUpsertCache[key] = cache
		postPhotoUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PostPhoto record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PostPhoto) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no PostPhoto provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), postPhotoPrimaryKeyMapping)
	sql := "DELETE FROM \"post_photos\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from post_photos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for post_photos")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q postPhotoQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no postPhotoQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from post_photos")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for post_photos")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PostPhotoSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(postPhotoBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), postPhotoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"post_photos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, postPhotoPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from postPhoto slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for post_photos")
	}

	if len(postPhotoAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PostPhoto) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPostPhoto(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PostPhotoSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PostPhotoSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), postPhotoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"post_photos\".* FROM \"post_photos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, postPhotoPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in PostPhotoSlice")
	}

	*o = slice

	return nil
}

// PostPhotoExists checks if the PostPhoto row exists.
func PostPhotoExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"post_photos\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if post_photos exists")
	}

	return exists, nil
}

// Exists checks if the PostPhoto row exists.
func (o *PostPhoto) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PostPhotoExists(ctx, exec, o.ID)
}
