// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PostVote is an object representing the database table.
type PostVote struct {
	UserID    string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	PostID    string    `boil:"post_id" json:"post_id" toml:"post_id" yaml:"post_id"`
	VoteType  string    `boil:"vote_type" json:"vote_type" toml:"vote_type" yaml:"vote_type"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *postVoteR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L postVoteL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PostVoteColumns = struct {
	UserID    string
	PostID    string
	VoteType  string
	CreatedAt string
}{
	UserID:    "user_id",
	PostID:    "post_id",
	VoteType:  "vote_type",
	CreatedAt: "created_at",
}

var PostVoteTableColumns = struct {
	UserID    string
	PostID    string
	VoteType  string
	CreatedAt string
}{
	UserID:    "post_votes.user_id",
	PostID:    "post_votes.post_id",
	VoteType:  "post_votes.vote_type",
	CreatedAt: "post_votes.created_at",
}

// Generated where

var PostVoteWhere = struct {
	UserID    whereHelperstring
	PostID    whereHelperstring
	VoteType  whereHelperstring
	CreatedAt whereHelpertime_Time
}{
	UserID:    whereHelperstring{field: "\"post_votes\".\"user_id\""},
	PostID:    whereHelperstring{field: "\"post_votes\".\"post_id\""},
	VoteType:  whereHelperstring{field: "\"post_votes\".\"vote_type\""},
	CreatedAt: whereHelpertime_Time{field: "\"post_votes\".\"created_at\""},
}

// PostVoteRels is where relationship names are stored.
var PostVoteRels = struct {
	Post string
}{
	Post: "Post",
}

// postVoteR is where relationships are stored.
type postVoteR struct {
	Post *Post `boil:"Post" json:"Post" toml:"Post" yaml:"Post"`
}

// NewStruct creates a new relationship struct
func (*postVoteR) NewStruct() *postVoteR {
	return &postVoteR{}
}

func (o *PostVote) GetPost() *Post {
	if o == nil {
		return nil
	}

	return o.R.GetPost()
}

func (r *postVoteR) GetPost() *Post {
	if r == nil {
		return nil
	}

	return r.Post
}

// postVoteL is where Load methods for each relationship are stored.
type postVoteL struct{}

var (
	postVoteAllColumns            = []string{"user_id", "post_id", "vote_type", "created_at"}
	postVoteColumnsWithoutDefault = []string{"user_id", "post_id", "vote_type"}
	postVoteColumnsWithDefault    = []string{"created_at"}
	postVotePrimaryKeyColumns     = []string{"user_id", "post_id"}
	postVoteGeneratedColumns      = []string{}
)

type (
	// PostVoteSlice is an alias for a slice of pointers to PostVote.
	// This should almost always be used instead of []PostVote.
	PostVoteSlice []*PostVote
	// PostVoteHook is the signature for custom PostVote hook methods
	PostVoteHook func(context.Context, boil.ContextExecutor, *PostVote) error

	postVoteQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	postVoteType                 = reflect.TypeOf(&PostVote{})
	postVoteMapping              = queries.MakeStructMapping(postVoteType)
	postVotePrimaryKeyMapping, _ = queries.BindMapping(postVoteType, postVoteMapping, postVotePrimaryKeyColumns)
	postVoteInsertCacheMut       sync.RWMutex
	postVoteInsertCache          = make(map[string]insertCache)
	postVoteUpdateCacheMut       sync.RWMutex
	postVoteUpdateCache          = make(map[string]updateCache)
	postVoteUpsertCacheMut       sync.RWMutex
	postVoteUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var postVoteAfterSelectMu sync.Mutex
var postVoteAfterSelectHooks []PostVoteHook

var postVoteBeforeInsertMu sync.Mutex
var postVoteBeforeInsertHooks []PostVoteHook
var postVoteAfterInsertMu sync.Mutex
var postVoteAfterInsertHooks []PostVoteHook

var postVoteBeforeUpdateMu sync.Mutex
var postVoteBeforeUpdateHooks []PostVoteHook
var postVoteAfterUpdateMu sync.Mutex
var postVoteAfterUpdateHooks []PostVoteHook

var postVoteBeforeDeleteMu sync.Mutex
var postVoteBeforeDeleteHooks []PostVoteHook
var postVoteAfterDeleteMu sync.Mutex
var postVoteAfterDeleteHooks []PostVoteHook

var postVoteBeforeUpsertMu sync.Mutex
var postVoteBeforeUpsertHooks []PostVoteHook
var postVoteAfterUpsertMu sync.Mutex
var postVoteAfterUpsertHooks []PostVoteHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PostVote) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postVoteAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PostVote) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postVoteBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PostVote) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postVoteAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PostVote) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postVoteBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PostVote) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postVoteAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PostVote) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postVoteBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PostVote) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postVoteAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PostVote) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postVoteBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PostVote) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range postVoteAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPostVoteHook registers your hook function for all future operations.
func AddPostVoteHook(hookPoint boil.HookPoint, postVoteHook PostVoteHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		postVoteAfterSelectMu.Lock()
		postVoteAfterSelectHooks = append(postVoteAfterSelectHooks, postVoteHook)
		postVoteAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		postVoteBeforeInsertMu.Lock()
		postVoteBeforeInsertHooks = append(postVoteBeforeInsertHooks, postVoteHook)
		postVoteBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		postVoteAfterInsertMu.Lock()
		postVoteAfterInsertHooks = append(postVoteAfterInsertHooks, postVoteHook)
		postVoteAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		postVoteBeforeUpdateMu.Lock()
		postVoteBeforeUpdateHooks = append(postVoteBeforeUpdateHooks, postVoteHook)
		postVoteBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		postVoteAfterUpdateMu.Lock()
		postVoteAfterUpdateHooks = append(postVoteAfterUpdateHooks, postVoteHook)
		postVoteAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		postVoteBeforeDeleteMu.Lock()
		postVoteBeforeDeleteHooks = append(postVoteBeforeDeleteHooks, postVoteHook)
		postVoteBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		postVoteAfterDeleteMu.Lock()
		postVoteAfterDeleteHooks = append(postVoteAfterDeleteHooks, postVoteHook)
		postVoteAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		postVoteBeforeUpsertMu.Lock()
		postVoteBeforeUpsertHooks = append(postVoteBeforeUpsertHooks, postVoteHook)
		postVoteBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		postVoteAfterUpsertMu.Lock()
		postVoteAfterUpsertHooks = append(postVoteAfterUpsertHooks, postVoteHook)
		postVoteAfterUpsertMu.Unlock()
	}
}

// One returns a single postVote record from the query.
func (q postVoteQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PostVote, error) {
	o := &PostVote{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for post_votes")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PostVote records from the query.
func (q postVoteQuery) All(ctx context.Context, exec boil.ContextExecutor) (PostVoteSlice, error) {
	var o []*PostVote

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to PostVote slice")
	}

	if len(postVoteAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PostVote records in the query.
func (q postVoteQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count post_votes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q postVoteQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if post_votes exists")
	}

	return count > 0, nil
}

// Post pointed to by the foreign key.
func (o *PostVote) Post(mods ...qm.QueryMod) postQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PostID),
	}

	queryMods = append(queryMods, mods...)

	return Posts(queryMods...)
}

// LoadPost allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (postVoteL) LoadPost(ctx context.Context, e boil.ContextExecutor, singular bool, maybePostVote any, mods queries.Applicator) error {
	var slice []*PostVote
	var object *PostVote

	if singular {
		var ok bool
		object, ok = maybePostVote.(*PostVote)
		if !ok {
			object = new(PostVote)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePostVote)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePostVote))
			}
		}
	} else {
		s, ok := maybePostVote.(*[]*PostVote)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePostVote)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePostVote))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &postVoteR{}
		}
		args[object.PostID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &postVoteR{}
			}

			args[obj.PostID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`posts`),
		qm.WhereIn(`posts.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Post")
	}

	var resultSlice []*Post
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Post")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for posts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for posts")
	}

	if len(postAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Post = foreign
		if foreign.R == nil {
			foreign.R = &postR{}
		}
		foreign.R.PostVotes = append(foreign.R.PostVotes, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PostID == foreign.ID {
				local.R.Post = foreign
				if foreign.R == nil {
					foreign.R = &postR{}
				}
				foreign.R.PostVotes = append(foreign.R.PostVotes, local)
				break
			}
		}
	}

	return nil
}

// SetPost of the postVote to the related item.
// Sets o.R.Post to related.
// Adds o to related.R.PostVotes.
func (o *PostVote) SetPost(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Post) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"post_votes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"post_id"}),
		strmangle.WhereClause("\"", "\"", 2, postVotePrimaryKeyColumns),
	)
	values := []any{related.ID, o.UserID, o.PostID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PostID = related.ID
	if o.R == nil {
		o.R = &postVoteR{
			Post: related,
		}
	} else {
		o.R.Post = related
	}

	if related.R == nil {
		related.R = &postR{
			PostVotes: PostVoteSlice{o},
		}
	} else {
		related.R.PostVotes = append(related.R.PostVotes, o)
	}

	return nil
}

// PostVotes retrieves all the records using an executor.
func PostVotes(mods ...qm.QueryMod) postVoteQuery {
	mods = append(mods, qm.From("\"post_votes\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"post_votes\".*"})
	}

	return postVoteQuery{q}
}

// FindPostVote retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPostVote(ctx context.Context, exec boil.ContextExecutor, userID string, postID string, selectCols ...string) (*PostVote, error) {
	postVoteObj := &PostVote{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"post_votes\" where \"user_id\"=$1 AND \"post_id\"=$2", sel,
	)

	q := queries.Raw(query, userID, postID)

	err := q.Bind(ctx, exec, postVoteObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from post_votes")
	}

	if err = postVoteObj.doAfterSelectHooks(ctx, exec); err != nil {
		return postVoteObj, err
	}

	return postVoteObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PostVote) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no post_votes provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(postVoteColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	postVoteInsertCacheMut.RLock()
	cache, cached := postVoteInsertCache[key]
	postVoteInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			postVoteAllColumns,
			postVoteColumnsWithDefault,
			postVoteColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(postVoteType, postVoteMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(postVoteType, postVoteMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"post_votes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"post_votes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into post_votes")
	}

	if !cached {
		postVoteInsertCacheMut.Lock()
		postVoteInsertCache[key] = cache
		postVoteInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PostVote.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PostVote) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	postVoteUpdateCacheMut.RLock()
	cache, cached := postVoteUpdateCache[key]
	postVoteUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			postVoteAllColumns,
			postVotePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update post_votes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"post_votes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, postVotePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(postVoteType, postVoteMapping, append(wl, postVotePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update post_votes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for post_votes")
	}

	if !cached {
		postVoteUpdateCacheMut.Lock()
		postVoteUpdateCache[key] = cache
		postVoteUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q postVoteQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for post_votes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for post_votes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PostVoteSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), postVotePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"post_votes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, postVotePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in postVote slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all postVote")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PostVote) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no post_votes provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(postVoteColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	postVoteUpsertCacheMut.RLock()
	cache, cached := postVoteUpsertCache[key]
	postVoteUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			postVoteAllColumns,
			postVoteColumnsWithDefault,
			postVoteColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			postVoteAllColumns,
			postVotePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert post_votes, could not build update column list")
		}

		ret := strmangle.SetComplement(postVoteAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(postVotePrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert post_votes, could not build conflict column list")
			}

			conflict = make([]string, len(postVotePrimaryKeyColumns))
			copy(conflict, postVotePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"post_votes\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(postVoteType, postVoteMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(postVoteType, postVoteMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert post_votes")
	}

	if !cached {
		postVoteUpsertCacheMut.Lock()
		postVoteUpsertCache[key] = cache
		postVoteUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PostVote record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PostVote) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no PostVote provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), postVotePrimaryKeyMapping)
	sql := "DELETE FROM \"post_votes\" WHERE \"user_id\"=$1 AND \"post_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from post_votes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for post_votes")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q postVoteQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no postVoteQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from post_votes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for post_votes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PostVoteSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(postVoteBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), postVotePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"post_votes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, postVotePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from postVote slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for post_votes")
	}

	if len(postVoteAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PostVote) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPostVote(ctx, exec, o.UserID, o.PostID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PostVoteSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PostVoteSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), postVotePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"post_votes\".* FROM \"post_votes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, postVotePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in PostVoteSlice")
	}

	*o = slice

	return nil
}

// PostVoteExists checks if the PostVote row exists.
func PostVoteExists(ctx context.Context, exec boil.ContextExecutor, userID string, postID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"post_votes\" where \"user_id\"=$1 AND \"post_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID, postID)
	}
	row := exec.QueryRowContext(ctx, sql, userID, postID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if post_votes exists")
	}

	return exists, nil
}

// Exists checks if the PostVote row exists.
func (o *PostVote) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PostVoteExists(ctx, exec, o.UserID, o.PostID)
}
