// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserSeenPost is an object representing the database table.
type UserSeenPost struct {
	UserID string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	PostID string    `boil:"post_id" json:"post_id" toml:"post_id" yaml:"post_id"`
	SeenAt time.Time `boil:"seen_at" json:"seen_at" toml:"seen_at" yaml:"seen_at"`

	R *userSeenPostR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userSeenPostL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserSeenPostColumns = struct {
	UserID string
	PostID string
	SeenAt string
}{
	UserID: "user_id",
	PostID: "post_id",
	SeenAt: "seen_at",
}

var UserSeenPostTableColumns = struct {
	UserID string
	PostID string
	SeenAt string
}{
	UserID: "user_seen_posts.user_id",
	PostID: "user_seen_posts.post_id",
	SeenAt: "user_seen_posts.seen_at",
}

// Generated where

var UserSeenPostWhere = struct {
	UserID whereHelperstring
	PostID whereHelperstring
	SeenAt whereHelpertime_Time
}{
	UserID: whereHelperstring{field: "\"user_seen_posts\".\"user_id\""},
	PostID: whereHelperstring{field: "\"user_seen_posts\".\"post_id\""},
	SeenAt: whereHelpertime_Time{field: "\"user_seen_posts\".\"seen_at\""},
}

// UserSeenPostRels is where relationship names are stored.
var UserSeenPostRels = struct {
}{}

// userSeenPostR is where relationships are stored.
type userSeenPostR struct {
}

// NewStruct creates a new relationship struct
func (*userSeenPostR) NewStruct() *userSeenPostR {
	return &userSeenPostR{}
}

// userSeenPostL is where Load methods for each relationship are stored.
type userSeenPostL struct{}

var (
	userSeenPostAllColumns            = []string{"user_id", "post_id", "seen_at"}
	userSeenPostColumnsWithoutDefault = []string{"user_id", "post_id"}
	userSeenPostColumnsWithDefault    = []string{"seen_at"}
	userSeenPostPrimaryKeyColumns     = []string{"user_id", "post_id"}
	userSeenPostGeneratedColumns      = []string{}
)

type (
	// UserSeenPostSlice is an alias for a slice of pointers to UserSeenPost.
	// This should almost always be used instead of []UserSeenPost.
	UserSeenPostSlice []*UserSeenPost
	// UserSeenPostHook is the signature for custom UserSeenPost hook methods
	UserSeenPostHook func(context.Context, boil.ContextExecutor, *UserSeenPost) error

	userSeenPostQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userSeenPostType                 = reflect.TypeOf(&UserSeenPost{})
	userSeenPostMapping              = queries.MakeStructMapping(userSeenPostType)
	userSeenPostPrimaryKeyMapping, _ = queries.BindMapping(userSeenPostType, userSeenPostMapping, userSeenPostPrimaryKeyColumns)
	userSeenPostInsertCacheMut       sync.RWMutex
	userSeenPostInsertCache          = make(map[string]insertCache)
	userSeenPostUpdateCacheMut       sync.RWMutex
	userSeenPostUpdateCache          = make(map[string]updateCache)
	userSeenPostUpsertCacheMut       sync.RWMutex
	userSeenPostUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userSeenPostAfterSelectMu sync.Mutex
var userSeenPostAfterSelectHooks []UserSeenPostHook

var userSeenPostBeforeInsertMu sync.Mutex
var userSeenPostBeforeInsertHooks []UserSeenPostHook
var userSeenPostAfterInsertMu sync.Mutex
var userSeenPostAfterInsertHooks []UserSeenPostHook

var userSeenPostBeforeUpdateMu sync.Mutex
var userSeenPostBeforeUpdateHooks []UserSeenPostHook
var userSeenPostAfterUpdateMu sync.Mutex
var userSeenPostAfterUpdateHooks []UserSeenPostHook

var userSeenPostBeforeDeleteMu sync.Mutex
var userSeenPostBeforeDeleteHooks []UserSeenPostHook
var userSeenPostAfterDeleteMu sync.Mutex
var userSeenPostAfterDeleteHooks []UserSeenPostHook

var userSeenPostBeforeUpsertMu sync.Mutex
var userSeenPostBeforeUpsertHooks []UserSeenPostHook
var userSeenPostAfterUpsertMu sync.Mutex
var userSeenPostAfterUpsertHooks []UserSeenPostHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserSeenPost) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userSeenPostAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserSeenPost) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userSeenPostBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserSeenPost) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userSeenPostAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserSeenPost) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userSeenPostBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserSeenPost) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userSeenPostAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserSeenPost) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userSeenPostBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserSeenPost) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userSeenPostAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserSeenPost) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userSeenPostBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserSeenPost) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userSeenPostAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserSeenPostHook registers your hook function for all future operations.
func AddUserSeenPostHook(hookPoint boil.HookPoint, userSeenPostHook UserSeenPostHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userSeenPostAfterSelectMu.Lock()
		userSeenPostAfterSelectHooks = append(userSeenPostAfterSelectHooks, userSeenPostHook)
		userSeenPostAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userSeenPostBeforeInsertMu.Lock()
		userSeenPostBeforeInsertHooks = append(userSeenPostBeforeInsertHooks, userSeenPostHook)
		userSeenPostBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userSeenPostAfterInsertMu.Lock()
		userSeenPostAfterInsertHooks = append(userSeenPostAfterInsertHooks, userSeenPostHook)
		userSeenPostAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userSeenPostBeforeUpdateMu.Lock()
		userSeenPostBeforeUpdateHooks = append(userSeenPostBeforeUpdateHooks, userSeenPostHook)
		userSeenPostBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userSeenPostAfterUpdateMu.Lock()
		userSeenPostAfterUpdateHooks = append(userSeenPostAfterUpdateHooks, userSeenPostHook)
		userSeenPostAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userSeenPostBeforeDeleteMu.Lock()
		userSeenPostBeforeDeleteHooks = append(userSeenPostBeforeDeleteHooks, userSeenPostHook)
		userSeenPostBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userSeenPostAfterDeleteMu.Lock()
		userSeenPostAfterDeleteHooks = append(userSeenPostAfterDeleteHooks, userSeenPostHook)
		userSeenPostAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userSeenPostBeforeUpsertMu.Lock()
		userSeenPostBeforeUpsertHooks = append(userSeenPostBeforeUpsertHooks, userSeenPostHook)
		userSeenPostBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userSeenPostAfterUpsertMu.Lock()
		userSeenPostAfterUpsertHooks = append(userSeenPostAfterUpsertHooks, userSeenPostHook)
		userSeenPostAfterUpsertMu.Unlock()
	}
}

// One returns a single userSeenPost record from the query.
func (q userSeenPostQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserSeenPost, error) {
	o := &UserSeenPost{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for user_seen_posts")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserSeenPost records from the query.
func (q userSeenPostQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserSeenPostSlice, error) {
	var o []*UserSeenPost

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to UserSeenPost slice")
	}

	if len(userSeenPostAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserSeenPost records in the query.
func (q userSeenPostQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count user_seen_posts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userSeenPostQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if user_seen_posts exists")
	}

	return count > 0, nil
}

// UserSeenPosts retrieves all the records using an executor.
func UserSeenPosts(mods ...qm.QueryMod) userSeenPostQuery {
	mods = append(mods, qm.From("\"user_seen_posts\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_seen_posts\".*"})
	}

	return userSeenPostQuery{q}
}

// FindUserSeenPost retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserSeenPost(ctx context.Context, exec boil.ContextExecutor, userID string, postID string, selectCols ...string) (*UserSeenPost, error) {
	userSeenPostObj := &UserSeenPost{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_seen_posts\" where \"user_id\"=$1 AND \"post_id\"=$2", sel,
	)

	q := queries.Raw(query, userID, postID)

	err := q.Bind(ctx, exec, userSeenPostObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from user_seen_posts")
	}

	if err = userSeenPostObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userSeenPostObj, err
	}

	return userSeenPostObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserSeenPost) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no user_seen_posts provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userSeenPostColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userSeenPostInsertCacheMut.RLock()
	cache, cached := userSeenPostInsertCache[key]
	userSeenPostInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userSeenPostAllColumns,
			userSeenPostColumnsWithDefault,
			userSeenPostColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userSeenPostType, userSeenPostMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userSeenPostType, userSeenPostMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_seen_posts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_seen_posts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into user_seen_posts")
	}

	if !cached {
		userSeenPostInsertCacheMut.Lock()
		userSeenPostInsertCache[key] = cache
		userSeenPostInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserSeenPost.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserSeenPost) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userSeenPostUpdateCacheMut.RLock()
	cache, cached := userSeenPostUpdateCache[key]
	userSeenPostUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userSeenPostAllColumns,
			userSeenPostPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update user_seen_posts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_seen_posts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userSeenPostPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userSeenPostType, userSeenPostMapping, append(wl, userSeenPostPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update user_seen_posts row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for user_seen_posts")
	}

	if !cached {
		userSeenPostUpdateCacheMut.Lock()
		userSeenPostUpdateCache[key] = cache
		userSeenPostUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userSeenPostQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for user_seen_posts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for user_seen_posts")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserSeenPostSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userSeenPostPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_seen_posts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userSeenPostPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in userSeenPost slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all userSeenPost")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserSeenPost) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodels: no user_seen_posts provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userSeenPostColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userSeenPostUpsertCacheMut.RLock()
	cache, cached := userSeenPostUpsertCache[key]
	userSeenPostUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userSeenPostAllColumns,
			userSeenPostColumnsWithDefault,
			userSeenPostColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userSeenPostAllColumns,
			userSeenPostPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert user_seen_posts, could not build update column list")
		}

		ret := strmangle.SetComplement(userSeenPostAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userSeenPostPrimaryKeyColumns) == 0 {
				return errors.New("dbmodels: unable to upsert user_seen_posts, could not build conflict column list")
			}

			conflict = make([]string, len(userSeenPostPrimaryKeyColumns))
			copy(conflict, userSeenPostPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_seen_posts\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userSeenPostType, userSeenPostMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userSeenPostType, userSeenPostMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert user_seen_posts")
	}

	if !cached {
		userSeenPostUpsertCacheMut.Lock()
		userSeenPostUpsertCache[key] = cache
		userSeenPostUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserSeenPost record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserSeenPost) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no UserSeenPost provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userSeenPostPrimaryKeyMapping)
	sql := "DELETE FROM \"user_seen_posts\" WHERE \"user_id\"=$1 AND \"post_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from user_seen_posts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for user_seen_posts")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userSeenPostQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no userSeenPostQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from user_seen_posts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for user_seen_posts")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserSeenPostSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userSeenPostBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userSeenPostPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_seen_posts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userSeenPostPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from userSeenPost slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for user_seen_posts")
	}

	if len(userSeenPostAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserSeenPost) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserSeenPost(ctx, exec, o.UserID, o.PostID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserSeenPostSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserSeenPostSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userSeenPostPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_seen_posts\".* FROM \"user_seen_posts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userSeenPostPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in UserSeenPostSlice")
	}

	*o = slice

	return nil
}

// UserSeenPostExists checks if the UserSeenPost row exists.
func UserSeenPostExists(ctx context.Context, exec boil.ContextExecutor, userID string, postID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_seen_posts\" where \"user_id\"=$1 AND \"post_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID, postID)
	}
	row := exec.QueryRowContext(ctx, sql, userID, postID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if user_seen_posts exists")
	}

	return exists, nil
}

// Exists checks if the UserSeenPost row exists.
func (o *UserSeenPost) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserSeenPostExists(ctx, exec, o.UserID, o.PostID)
}
