apiVersion: v1
kind: Secret
metadata:
    name: identity-service-secret
    namespace: yetbota
    labels:
        app.kubernetes.io/name: identity-service
        app.kubernetes.io/part-of: yetbota
type: Opaque
stringData:
    debug: ENC[AES256_GCM,data:D9z1JA==,iv:NnS1eYMeZb08mu7zThR82ayNfKL4nF/K2QbOIk5rnas=,tag:P9H1SShhqj5Vr7SuRZINLg==,type:str]
    corsHosts: ENC[AES256_GCM,data:tSfMEI5oELHK,iv:RMJQHixHNPhs6rvoevJHZH1erZur7KaWHg1vJJTe3tU=,tag:jscdsP9nvxKQgUJ/MwsEww==,type:str]
    jwtAccessTokenSecret: ENC[AES256_GCM,data:pTecI1pQqYWTjH24qQSR1Q6NZkaFcZNJ/8OOYrvQKHIbliPEpkrxPxPoSg==,iv:K2Srp+xigLhqu3rXB9ADNm2BGSzlipupXd7CP1SnNMU=,tag:3COWahQ6I7lk1ZCczvftkw==,type:str]
    jwtAccessTokenExpiration: ENC[AES256_GCM,data:zpx5,iv:ghhk38zp3twu+07W/Xf6BWz4qbQva4zexXx+oL5nX+M=,tag:hC9WFj6J+Xe6Fmv8dVTZJQ==,type:str]
    jwtRefreshTokenSecret: ENC[AES256_GCM,data:PuGcHqilR8ZwA0IOKQUdOhNw5GE7obZ5yoW0TFdijGi11vyexQ5iLP61hQ==,iv:H5IlimRACnZGR9ZzAj45w8u1Fy57gxbV0akRO9b/cj0=,tag:Fj1K6FV+3sXUV44fyhJtUw==,type:str]
    jwtRefreshTokenExpiration: ENC[AES256_GCM,data:KuNOB5sx,iv:/OBJ4v/zEqJV2vMPp/w4w3GK/lNNFAkuDKfBkTBvWaM=,tag:l8/6lAJxRXouOOKkvPEH+w==,type:str]
    postgresHost: ENC[AES256_GCM,data:s6zN+7nhUIiv7w++q24VPBJCgN8YpsYNpa31qk8dYQiaWp5PG5r1/w==,iv:LULacbBV8dO11zmSFDT4jG0Byn7v8XuutcNT+cWyBY4=,tag:T7WIhdiNIfXUdTkQ69sstw==,type:str]
    postgresPort: ENC[AES256_GCM,data:vtvDgg==,iv:Ozf9cyYq6F911kNkgZFeo3ACxNr1FrrDlILmmXBkEi4=,tag:FTPcRGqQz7n6vmS9TvCF9Q==,type:str]
    postgresDB: ENC[AES256_GCM,data:X/xOQfsrrKEzvQ==,iv:dFjzFRvlmmbnHlzuH4G4/+5ev4VxvpbA+5l9yXTdxV4=,tag:Ee8alipvDyokqHK3E/4rjw==,type:str]
    postgresUser: ENC[AES256_GCM,data:hjOfWfao6w==,iv:g7o+6byxPoZVCURXhTUUE3AbKmH94z3QkNHaCbFOqU4=,tag:SXsDp5gMy6KIhL6RUrSnDQ==,type:str]
    postgresPassword: ENC[AES256_GCM,data:sADHjvelO80qYsgIyt3raUt+8J7u4p5wEd8nuNvNkpezKJh9KhpPxxbwCg==,iv:AH6Om0AGqu8IU+l0c9OiOgwZMPqOJXwFErEyxG6qpaI=,tag:vi6S04rrP9MoCLvr5oDiTg==,type:str]
    redisAddress: ENC[AES256_GCM,data:JIf6egBsHOaapVK0cXvTBM65VRXmskuXqXiHpPs3DTpaGKgmkCYqhVGF,iv:WG0uK6+Lp4GjB3NlDNTow6z1IYjCRvtRrs7ebg1knoo=,tag:jObzGigJUb80BsgB2jJ2Rw==,type:str]
    redisPassword: ENC[AES256_GCM,data:sxLTKdKAnhhc+AWbIl1D5B3RAJ8Ch+2y3S15L0x3,iv:wk7zbu8/vrLEzjt27/2bOw4sCZcoL287z8UYs0ZHPhQ=,tag:8HFIPcptv0v7YpeGH+L5CQ==,type:str]
    redisPoolTimeout: ENC[AES256_GCM,data:ZpYs,iv:PAVyfMfXG/KQzA5E/9CRw9wFlVv1zmXvJshiw0wjlv4=,tag:kz8FAAyL1ZntKforN4LlFg==,type:str]
    redisIdleTimeout: ENC[AES256_GCM,data:JIuCWA==,iv:penLyaKrUVTtdXrXyG93ULvotTP0RO+QG/3DqfGywJ8=,tag:G2rL8nkPp4FYmycSqfvdZQ==,type:str]
    redisReadTimeout: ENC[AES256_GCM,data:JxE=,iv:B+jtyue9fLDkg+wP9+R8VKwBxf6UZocOJvACIH5Frn4=,tag:w3RreSEITrRYe1Du/SPaJw==,type:str]
    redisWriteTimeout: ENC[AES256_GCM,data:8H0=,iv:9qlRcUPu8IP5n/Zrvd4ySPD1ExNqX9rMUJ3mISDZP4M=,tag:FIiI+g7fq0/X4z3QYXCVzw==,type:str]
    otpTTL: ENC[AES256_GCM,data:TLaO,iv:swpB+mIPNRrUkuQMWAWljnIk0YI3fF3IsLKjRO/+xOM=,tag:yRJV5VUX02QRSjt9scXhkQ==,type:str]
    otpLockRequestTime: ENC[AES256_GCM,data:27s=,iv:XMMcKYLoUXA7daNQ2gw1AaN/qp5agt+LLUEslumecHI=,tag:7vFHhAyWivh4WVwexmSrvw==,type:str]
    otpLockInvalidTime: ENC[AES256_GCM,data:8FVH,iv:PulTbD8g7szNkNBas7h6oNrqcAv2LP9w8wpTJwB90nk=,tag:70ie+H4Zir+wR9V8m0U5sA==,type:str]
    neo4jURI: ENC[AES256_GCM,data:0PWf2Hcw5aNDo21f9Iq4nzDg98a3S8/oZE0/lwE86RcfvyretnV9fZXk9nq+KEuHtg==,iv:HEBqsnMuyrZd4mREw9WPjL+8E3S3A4Sihn4ow3BXxwo=,tag:VbQeMm2Aeitfk5d/bjbwDw==,type:str]
    neo4jUsername: ENC[AES256_GCM,data:8G174hI=,iv:yGzBBnv8djxqI7usMH7tYEpaqRWxd93h19NPnm8zBP0=,tag:JOmw6zV5kqmY16Hx+cCFhw==,type:str]
    neo4jPassword: ENC[AES256_GCM,data:N1F9kgVXtqEsiHMNe2VXl+JD1SCSrPcG6/BbYSuEr3uhu3SKAeHBLYKgxA==,iv:92g7ST0U5Bv/4CO1yrYFekuZ/6TQIefqi3vOXmK/pSc=,tag:TrxbfJYnd6iREYRhqAKNaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aaplqegrnem7x5k89rtn2mfrajkjkapf0lamfw6fdjk9ru4e65cs7qnq7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNHJ5YXdteHhMYlM3MHlX
            L2EwTjVib2Z5bk9lQXVPY0hmSnNiMm9zblNzClY0SThLK09XakRGWE84WHBra0ls
            NzlYbUhIbTFWMWU0MWxwMjRJdE12elkKLS0tIE9qc29rNTFSUlFmYVBxcjZmbWVo
            ZDNZdEZlZG1VNnpoRWVLL1ZLNkJ6YTAK0UHRUpaaItK/iGsgr/6KbNBgaP+JN60P
            eh6vNcN4dp70oWbfoaJv1gQuaUxKRfSkP145KfFeziWuoM4J6tTlrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:20:55Z"
    mac: ENC[AES256_GCM,data:Ai/hHsbKp9mUhhZRx6npWI08PveT5vKBiOO4bdHZc7rPtQ4LFIREu4bXRFQLZVqSa/3hPRbWsGSWRZbAckfLrYoZ/pic68EQrqyojKiq2tJ1kegmtOBbEuVXvmjwQIE5B49FOvCfMYl4V6IEGlKmPGshNke6iy9nqzdw/gS1c2s=,iv:99xiIBlVWnrXMyMRgaxpQxAnbICAPGRVR0E93i84lw8=,tag:+5YKU1b1sYUVAeHWUXyo7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
