apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: yetbota-infra
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: yetbota
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
