apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: yetbota-infra
    labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: yetbota
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:YIHqs37KWLIt3L2EG478PT2QybHrRIEetmlJfN8O,iv:3qBVOov9bD7FBfYfEwZjPhUCtTxVPZyftKyjB40rscM=,tag:sdreYIB6dXsbYzTUOtNWiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aaplqegrnem7x5k89rtn2mfrajkjkapf0lamfw6fdjk9ru4e65cs7qnq7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SUVMZFBuWHZNcVAyQjk5
            YjFXd25FcXk0V0RkRC8zNmRDazBGUHQrSmxZCm5RaEljQXB1OGdNc3BOUUVvWlRE
            RlZJa3NCSHNxeWx0T2dLU09oU3N4VFUKLS0tIFZDcktOMXd5cDlVa1JCWXpPNHd0
            bVFVK3lvS0JUSlFEaTBnekRFU1Z5b1EKvKG6PcK2H7JZmOiGhgLzVAyz6dG/Yx/Q
            8fujXP+CWgBR7sP4Dg2kx6rviZ915+JED9URZQVngzeTNJuH3KT8Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:16:13Z"
    mac: ENC[AES256_GCM,data:CDrxkqVoVsucw+bX2CLh+/5zUjzUBa1VAfrlZyTosd50cmQ+9Z5JBtNg5H7cEBRdpUuoJT6aY8wUSNMGbSKrLqqB3h2+hfL/mbLmJ2e6gcKqFDwAwId3inuNdNmQ9DRFxyLlYi18UF7fBNBNggX4KqHRnATK97JbOyxPB17nUk4=,iv:hzNgHgUFliBNri4tQGCJE928XTnGmJL4Ndl9CWGcrSw=,tag:T22Iai3Goh9UONnUgxPaNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
