apiVersion: v1
kind: Secret
metadata:
    name: weaviate-secret
    namespace: yetbota-infra
    labels:
        app.kubernetes.io/name: weaviate
        app.kubernetes.io/part-of: yetbota
type: Opaque
stringData:
    AUTHENTICATION_APIKEY_ALLOWED_KEYS: ENC[AES256_GCM,data:Y9DWbjr4ar9ot2qMH4vSTYXla6BIkbprS2+It4Ra5Di46ialrP8aosHOIg==,iv:5Ma78YxS1UesQsMpiRwXMXNnGS426GhHFgSPRzJL2jo=,tag:OgmaPabzWRZ1raIuXGAzLw==,type:str]
sops:
    age:
        - recipient: age1aaplqegrnem7x5k89rtn2mfrajkjkapf0lamfw6fdjk9ru4e65cs7qnq7n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZk4xRXBUNFBsSUswRjFv
            azk2SGI0cmdoa3lneWNTZU5YRkVSZ0lMcEZnCnF5YS9sbUN4Z3VwTmtGK2YwL3ZB
            YWkxMmF3WDNnMG5vNHlCOThXWjFZOFEKLS0tIEpJMFd1RDlibWhvYnNxR0J0N21a
            d1hMdTI5NHkzMHBmN2YyOEN5YWR5MlEKg8z2Yp76P2tDfMry/BoS6E8oasFjrnaX
            WkLCZHem7TWxYAvIQdD86AjcuAYNqA+lkZsJ27zOS4L4IjcnKCNS9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T12:43:44Z"
    mac: ENC[AES256_GCM,data:BIraWzrlZIuGXSCIa/W4C5xfrw4W5WL8Dvhc55otizWATCMX910qebzAYe20rcklbMSlWNSDlUScGNTh/Wjx5XJTTBDYWsb7Zuw2espNu/ximwDNhHnCOPjSBt+mjAvn34iwaJOGntknIkpgNAMVQuRr5i1Qu2oUcBA2eNLD2UA=,iv:vepnWVkpvjBwtSoGQlGRfuCCOK0pfMntYXmSJiMO0eg=,tag:1K1NesK348mRroQ/yDHyDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
