apiVersion: v1
kind: Service
metadata:
  name: weaviate
  namespace: yetbota-infra
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/part-of: yetbota
spec:
  selector:
    app.kubernetes.io/name: weaviate
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
